import type { ThemeDefinition, ThemeOwnerType } from '../contracts'
import { THEME_MANAGER_VERSION, THEME_VOCABULARY_VERSION } from './theme-release'

// Generated from assets/css/theme/theme-default.css: every --ui-* token except the base
// spacing unit (--ui-spacing), which is not settable by design.
// Generated from assets/css/theme/theme-default.css: every --ui-* token except the base
// spacing unit (--ui-spacing), which is not settable by design.
export const CANONICAL_THEME_CARDINALITY = {
  "colour": 490,
  "typography": 45,
  "spacing": 9,
  "radii": 16,
  "effects": 626,
  "responsive": 23,
  "borders": 9,
  "motion": 22,
  "total": 1240
} as const

const canonicalPresentation = {
  "colour": {
    "roles": {
      "fill-floor": true,
      "fill-base": true,
      "fill-primary": true,
      "fill-secondary": true,
      "fill-tertiary": true,
      "fill-accent": true,
      "fill-muted": true,
      "fill-input": true,
      "fill-link": true,
      "fill-success": true,
      "fill-info": true,
      "fill-warning": true,
      "fill-error": true,
      "fill-notification": true,
      "pen-floor": true,
      "pen-base": true,
      "pen-primary": true,
      "pen-secondary": true,
      "pen-tertiary": true,
      "pen-accent": true,
      "pen-muted": true,
      "pen-input": true,
      "pen-link": true,
      "pen-success": true,
      "pen-info": true,
      "pen-warning": true,
      "pen-error": true,
      "pen-notification": true,
      "edge-floor": true,
      "edge-base": true,
      "edge-primary": true,
      "edge-secondary": true,
      "edge-tertiary": true,
      "edge-accent": true,
      "edge-muted": true,
      "edge-input": true,
      "edge-link": true,
      "edge-success": true,
      "edge-info": true,
      "edge-warning": true,
      "edge-error": true,
      "edge-notification": true
    }
  },
  "typography": {
    "families": {
      "sans": "\"Inter\", ui-sans-serif, system-ui, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
      "serif": "\"Merriweather\", ui-serif, Georgia, \"Times New Roman\", serif",
      "mono": "\"Fira Code\", ui-monospace, \"SFMono-Regular\", Menlo, Consolas, monospace",
      "mono-feature-settings": "\"liga\" 0, \"calt\" 0"
    },
    "sizes": {
      "xs": "0.75rem",
      "xs-line-height": "1rem",
      "sm": "0.875rem",
      "sm-line-height": "1.25rem",
      "base": "1rem",
      "base-line-height": "1.5rem",
      "lg": "1.125rem",
      "lg-line-height": "1.75rem",
      "xl": "1.25rem",
      "xl-line-height": "1.75rem",
      "2xl": "1.5rem",
      "2xl-line-height": "2rem",
      "3xl": "1.875rem",
      "3xl-line-height": "2.25rem",
      "4xl": "2.25rem",
      "4xl-line-height": "2.5rem",
      "5xl": "3rem",
      "5xl-line-height": "1.1",
      "body": "var(--ui-text-base)",
      "body-line-height": "var(--ui-text-base-line-height)",
      "label": "var(--ui-text-sm)",
      "label-line-height": "var(--ui-text-sm-line-height)",
      "caption": "var(--ui-text-xs)",
      "caption-line-height": "var(--ui-text-xs-line-height)",
      "heading": "var(--ui-text-2xl)",
      "heading-line-height": "var(--ui-text-2xl-line-height)",
      "title": "var(--ui-text-3xl)",
      "title-line-height": "var(--ui-text-3xl-line-height)"
    },
    "weights": {
      "normal": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700"
    },
    "tracking": {
      "tight": "-0.015em",
      "normal": "0",
      "wide": "0.025em",
      "caps": "0.06em"
    },
    "leading": {
      "none": "1",
      "tight": "1.25",
      "snug": "1.375",
      "normal": "1.5",
      "relaxed": "1.625"
    }
  },
  "spacing": {
    "step-3xs": "0.125rem",
    "step-2xs": "0.25rem",
    "step-xs": "0.5rem",
    "step-sm": "0.75rem",
    "step-md": "1rem",
    "step-lg": "1.5rem",
    "step-xl": "2rem",
    "step-2xl": "3rem",
    "step-3xl": "4rem"
  },
  "radii": {
    "none": "0",
    "xs": "0.125rem",
    "sm": "0.25rem",
    "md": "0.375rem",
    "lg": "0.5rem",
    "xl": "0.75rem",
    "2xl": "1rem",
    "3xl": "1.5rem",
    "full": "calc(infinity * 1px)",
    "DEFAULT": "var(--ui-radius-md)",
    "tooltip": "var(--ui-radius-sm)",
    "control": "var(--ui-radius-md)",
    "card": "var(--ui-radius-lg)",
    "panel": "var(--ui-radius-xl)",
    "dialog": "var(--ui-radius-2xl)",
    "pill": "var(--ui-radius-full)"
  },
  "effects": {
    "shadow": {
      "xs-light": "var(--ui-shadow-xs-base-light)",
      "sm-light": "var(--ui-shadow-sm-base-light)",
      "md-light": "var(--ui-shadow-md-base-light)",
      "lg-light": "var(--ui-shadow-lg-base-light)",
      "xl-light": "var(--ui-shadow-xl-base-light)",
      "raised-light": "var(--ui-shadow-sm-light)",
      "lifted-light": "var(--ui-shadow-md-light)",
      "overlay-light": "var(--ui-shadow-lg-light)",
      "modal-light": "var(--ui-shadow-xl-light)",
      "xs-floor-light": "0 1px 1px 0 var(--ui-fill-floor-shadow-light)",
      "sm-floor-light": "0 2px 5px -1px var(--ui-fill-floor-shadow-light), 0 1px 2px -1px var(--ui-fill-floor-shadow-light)",
      "md-floor-light": "0 5px 10px -2px var(--ui-fill-floor-shadow-light), 0 2px 4px -2px var(--ui-fill-floor-shadow-light)",
      "lg-floor-light": "0 12px 18px -4px var(--ui-fill-floor-shadow-light), 0 4px 6px -4px var(--ui-fill-floor-shadow-light)",
      "xl-floor-light": "0 22px 30px -6px var(--ui-fill-floor-shadow-light), 0 8px 12px -8px var(--ui-fill-floor-shadow-light)",
      "xs-base-light": "0 1px 1px 0 var(--ui-fill-base-shadow-light)",
      "sm-base-light": "0 2px 5px -1px var(--ui-fill-base-shadow-light), 0 1px 2px -1px var(--ui-fill-base-shadow-light)",
      "md-base-light": "0 5px 10px -2px var(--ui-fill-base-shadow-light), 0 2px 4px -2px var(--ui-fill-base-shadow-light)",
      "lg-base-light": "0 12px 18px -4px var(--ui-fill-base-shadow-light), 0 4px 6px -4px var(--ui-fill-base-shadow-light)",
      "xl-base-light": "0 22px 30px -6px var(--ui-fill-base-shadow-light), 0 8px 12px -8px var(--ui-fill-base-shadow-light)",
      "xs-primary-light": "0 1px 1px 0 var(--ui-fill-primary-shadow-light)",
      "sm-primary-light": "0 2px 5px -1px var(--ui-fill-primary-shadow-light), 0 1px 2px -1px var(--ui-fill-primary-shadow-light)",
      "md-primary-light": "0 5px 10px -2px var(--ui-fill-primary-shadow-light), 0 2px 4px -2px var(--ui-fill-primary-shadow-light)",
      "lg-primary-light": "0 12px 18px -4px var(--ui-fill-primary-shadow-light), 0 4px 6px -4px var(--ui-fill-primary-shadow-light)",
      "xl-primary-light": "0 22px 30px -6px var(--ui-fill-primary-shadow-light), 0 8px 12px -8px var(--ui-fill-primary-shadow-light)",
      "xs-secondary-light": "0 1px 1px 0 var(--ui-fill-secondary-shadow-light)",
      "sm-secondary-light": "0 2px 5px -1px var(--ui-fill-secondary-shadow-light), 0 1px 2px -1px var(--ui-fill-secondary-shadow-light)",
      "md-secondary-light": "0 5px 10px -2px var(--ui-fill-secondary-shadow-light), 0 2px 4px -2px var(--ui-fill-secondary-shadow-light)",
      "lg-secondary-light": "0 12px 18px -4px var(--ui-fill-secondary-shadow-light), 0 4px 6px -4px var(--ui-fill-secondary-shadow-light)",
      "xl-secondary-light": "0 22px 30px -6px var(--ui-fill-secondary-shadow-light), 0 8px 12px -8px var(--ui-fill-secondary-shadow-light)",
      "xs-tertiary-light": "0 1px 1px 0 var(--ui-fill-tertiary-shadow-light)",
      "sm-tertiary-light": "0 2px 5px -1px var(--ui-fill-tertiary-shadow-light), 0 1px 2px -1px var(--ui-fill-tertiary-shadow-light)",
      "md-tertiary-light": "0 5px 10px -2px var(--ui-fill-tertiary-shadow-light), 0 2px 4px -2px var(--ui-fill-tertiary-shadow-light)",
      "lg-tertiary-light": "0 12px 18px -4px var(--ui-fill-tertiary-shadow-light), 0 4px 6px -4px var(--ui-fill-tertiary-shadow-light)",
      "xl-tertiary-light": "0 22px 30px -6px var(--ui-fill-tertiary-shadow-light), 0 8px 12px -8px var(--ui-fill-tertiary-shadow-light)",
      "xs-accent-light": "0 1px 1px 0 var(--ui-fill-accent-shadow-light)",
      "sm-accent-light": "0 2px 5px -1px var(--ui-fill-accent-shadow-light), 0 1px 2px -1px var(--ui-fill-accent-shadow-light)",
      "md-accent-light": "0 5px 10px -2px var(--ui-fill-accent-shadow-light), 0 2px 4px -2px var(--ui-fill-accent-shadow-light)",
      "lg-accent-light": "0 12px 18px -4px var(--ui-fill-accent-shadow-light), 0 4px 6px -4px var(--ui-fill-accent-shadow-light)",
      "xl-accent-light": "0 22px 30px -6px var(--ui-fill-accent-shadow-light), 0 8px 12px -8px var(--ui-fill-accent-shadow-light)",
      "xs-muted-light": "0 1px 1px 0 var(--ui-fill-muted-shadow-light)",
      "sm-muted-light": "0 2px 5px -1px var(--ui-fill-muted-shadow-light), 0 1px 2px -1px var(--ui-fill-muted-shadow-light)",
      "md-muted-light": "0 5px 10px -2px var(--ui-fill-muted-shadow-light), 0 2px 4px -2px var(--ui-fill-muted-shadow-light)",
      "lg-muted-light": "0 12px 18px -4px var(--ui-fill-muted-shadow-light), 0 4px 6px -4px var(--ui-fill-muted-shadow-light)",
      "xl-muted-light": "0 22px 30px -6px var(--ui-fill-muted-shadow-light), 0 8px 12px -8px var(--ui-fill-muted-shadow-light)",
      "xs-input-light": "0 1px 1px 0 var(--ui-fill-input-shadow-light)",
      "sm-input-light": "0 2px 5px -1px var(--ui-fill-input-shadow-light), 0 1px 2px -1px var(--ui-fill-input-shadow-light)",
      "md-input-light": "0 5px 10px -2px var(--ui-fill-input-shadow-light), 0 2px 4px -2px var(--ui-fill-input-shadow-light)",
      "lg-input-light": "0 12px 18px -4px var(--ui-fill-input-shadow-light), 0 4px 6px -4px var(--ui-fill-input-shadow-light)",
      "xl-input-light": "0 22px 30px -6px var(--ui-fill-input-shadow-light), 0 8px 12px -8px var(--ui-fill-input-shadow-light)",
      "xs-link-light": "0 1px 1px 0 var(--ui-fill-link-shadow-light)",
      "sm-link-light": "0 2px 5px -1px var(--ui-fill-link-shadow-light), 0 1px 2px -1px var(--ui-fill-link-shadow-light)",
      "md-link-light": "0 5px 10px -2px var(--ui-fill-link-shadow-light), 0 2px 4px -2px var(--ui-fill-link-shadow-light)",
      "lg-link-light": "0 12px 18px -4px var(--ui-fill-link-shadow-light), 0 4px 6px -4px var(--ui-fill-link-shadow-light)",
      "xl-link-light": "0 22px 30px -6px var(--ui-fill-link-shadow-light), 0 8px 12px -8px var(--ui-fill-link-shadow-light)",
      "xs-success-light": "0 1px 1px 0 var(--ui-fill-success-shadow-light)",
      "sm-success-light": "0 2px 5px -1px var(--ui-fill-success-shadow-light), 0 1px 2px -1px var(--ui-fill-success-shadow-light)",
      "md-success-light": "0 5px 10px -2px var(--ui-fill-success-shadow-light), 0 2px 4px -2px var(--ui-fill-success-shadow-light)",
      "lg-success-light": "0 12px 18px -4px var(--ui-fill-success-shadow-light), 0 4px 6px -4px var(--ui-fill-success-shadow-light)",
      "xl-success-light": "0 22px 30px -6px var(--ui-fill-success-shadow-light), 0 8px 12px -8px var(--ui-fill-success-shadow-light)",
      "xs-info-light": "0 1px 1px 0 var(--ui-fill-info-shadow-light)",
      "sm-info-light": "0 2px 5px -1px var(--ui-fill-info-shadow-light), 0 1px 2px -1px var(--ui-fill-info-shadow-light)",
      "md-info-light": "0 5px 10px -2px var(--ui-fill-info-shadow-light), 0 2px 4px -2px var(--ui-fill-info-shadow-light)",
      "lg-info-light": "0 12px 18px -4px var(--ui-fill-info-shadow-light), 0 4px 6px -4px var(--ui-fill-info-shadow-light)",
      "xl-info-light": "0 22px 30px -6px var(--ui-fill-info-shadow-light), 0 8px 12px -8px var(--ui-fill-info-shadow-light)",
      "xs-warning-light": "0 1px 1px 0 var(--ui-fill-warning-shadow-light)",
      "sm-warning-light": "0 2px 5px -1px var(--ui-fill-warning-shadow-light), 0 1px 2px -1px var(--ui-fill-warning-shadow-light)",
      "md-warning-light": "0 5px 10px -2px var(--ui-fill-warning-shadow-light), 0 2px 4px -2px var(--ui-fill-warning-shadow-light)",
      "lg-warning-light": "0 12px 18px -4px var(--ui-fill-warning-shadow-light), 0 4px 6px -4px var(--ui-fill-warning-shadow-light)",
      "xl-warning-light": "0 22px 30px -6px var(--ui-fill-warning-shadow-light), 0 8px 12px -8px var(--ui-fill-warning-shadow-light)",
      "xs-error-light": "0 1px 1px 0 var(--ui-fill-error-shadow-light)",
      "sm-error-light": "0 2px 5px -1px var(--ui-fill-error-shadow-light), 0 1px 2px -1px var(--ui-fill-error-shadow-light)",
      "md-error-light": "0 5px 10px -2px var(--ui-fill-error-shadow-light), 0 2px 4px -2px var(--ui-fill-error-shadow-light)",
      "lg-error-light": "0 12px 18px -4px var(--ui-fill-error-shadow-light), 0 4px 6px -4px var(--ui-fill-error-shadow-light)",
      "xl-error-light": "0 22px 30px -6px var(--ui-fill-error-shadow-light), 0 8px 12px -8px var(--ui-fill-error-shadow-light)",
      "xs-notification-light": "0 1px 1px 0 var(--ui-fill-notification-shadow-light)",
      "sm-notification-light": "0 2px 5px -1px var(--ui-fill-notification-shadow-light), 0 1px 2px -1px var(--ui-fill-notification-shadow-light)",
      "md-notification-light": "0 5px 10px -2px var(--ui-fill-notification-shadow-light), 0 2px 4px -2px var(--ui-fill-notification-shadow-light)",
      "lg-notification-light": "0 12px 18px -4px var(--ui-fill-notification-shadow-light), 0 4px 6px -4px var(--ui-fill-notification-shadow-light)",
      "xl-notification-light": "0 22px 30px -6px var(--ui-fill-notification-shadow-light), 0 8px 12px -8px var(--ui-fill-notification-shadow-light)",
      "xs-dark": "var(--ui-shadow-xs-base-dark)",
      "sm-dark": "var(--ui-shadow-sm-base-dark)",
      "md-dark": "var(--ui-shadow-md-base-dark)",
      "lg-dark": "var(--ui-shadow-lg-base-dark)",
      "xl-dark": "var(--ui-shadow-xl-base-dark)",
      "raised-dark": "var(--ui-shadow-sm-dark)",
      "lifted-dark": "var(--ui-shadow-md-dark)",
      "overlay-dark": "var(--ui-shadow-lg-dark)",
      "modal-dark": "var(--ui-shadow-xl-dark)",
      "xs-floor-dark": "0 1px 1px 0 var(--ui-fill-floor-shadow-dark)",
      "sm-floor-dark": "0 2px 5px -1px var(--ui-fill-floor-shadow-dark), 0 1px 2px -1px var(--ui-fill-floor-shadow-dark)",
      "md-floor-dark": "0 5px 10px -2px var(--ui-fill-floor-shadow-dark), 0 2px 4px -2px var(--ui-fill-floor-shadow-dark)",
      "lg-floor-dark": "0 12px 18px -4px var(--ui-fill-floor-shadow-dark), 0 4px 6px -4px var(--ui-fill-floor-shadow-dark)",
      "xl-floor-dark": "0 22px 30px -6px var(--ui-fill-floor-shadow-dark), 0 8px 12px -8px var(--ui-fill-floor-shadow-dark)",
      "xs-base-dark": "0 1px 1px 0 var(--ui-fill-base-shadow-dark)",
      "sm-base-dark": "0 2px 5px -1px var(--ui-fill-base-shadow-dark), 0 1px 2px -1px var(--ui-fill-base-shadow-dark)",
      "md-base-dark": "0 5px 10px -2px var(--ui-fill-base-shadow-dark), 0 2px 4px -2px var(--ui-fill-base-shadow-dark)",
      "lg-base-dark": "0 12px 18px -4px var(--ui-fill-base-shadow-dark), 0 4px 6px -4px var(--ui-fill-base-shadow-dark)",
      "xl-base-dark": "0 22px 30px -6px var(--ui-fill-base-shadow-dark), 0 8px 12px -8px var(--ui-fill-base-shadow-dark)",
      "xs-primary-dark": "0 1px 1px 0 var(--ui-fill-primary-shadow-dark)",
      "sm-primary-dark": "0 2px 5px -1px var(--ui-fill-primary-shadow-dark), 0 1px 2px -1px var(--ui-fill-primary-shadow-dark)",
      "md-primary-dark": "0 5px 10px -2px var(--ui-fill-primary-shadow-dark), 0 2px 4px -2px var(--ui-fill-primary-shadow-dark)",
      "lg-primary-dark": "0 12px 18px -4px var(--ui-fill-primary-shadow-dark), 0 4px 6px -4px var(--ui-fill-primary-shadow-dark)",
      "xl-primary-dark": "0 22px 30px -6px var(--ui-fill-primary-shadow-dark), 0 8px 12px -8px var(--ui-fill-primary-shadow-dark)",
      "xs-secondary-dark": "0 1px 1px 0 var(--ui-fill-secondary-shadow-dark)",
      "sm-secondary-dark": "0 2px 5px -1px var(--ui-fill-secondary-shadow-dark), 0 1px 2px -1px var(--ui-fill-secondary-shadow-dark)",
      "md-secondary-dark": "0 5px 10px -2px var(--ui-fill-secondary-shadow-dark), 0 2px 4px -2px var(--ui-fill-secondary-shadow-dark)",
      "lg-secondary-dark": "0 12px 18px -4px var(--ui-fill-secondary-shadow-dark), 0 4px 6px -4px var(--ui-fill-secondary-shadow-dark)",
      "xl-secondary-dark": "0 22px 30px -6px var(--ui-fill-secondary-shadow-dark), 0 8px 12px -8px var(--ui-fill-secondary-shadow-dark)",
      "xs-tertiary-dark": "0 1px 1px 0 var(--ui-fill-tertiary-shadow-dark)",
      "sm-tertiary-dark": "0 2px 5px -1px var(--ui-fill-tertiary-shadow-dark), 0 1px 2px -1px var(--ui-fill-tertiary-shadow-dark)",
      "md-tertiary-dark": "0 5px 10px -2px var(--ui-fill-tertiary-shadow-dark), 0 2px 4px -2px var(--ui-fill-tertiary-shadow-dark)",
      "lg-tertiary-dark": "0 12px 18px -4px var(--ui-fill-tertiary-shadow-dark), 0 4px 6px -4px var(--ui-fill-tertiary-shadow-dark)",
      "xl-tertiary-dark": "0 22px 30px -6px var(--ui-fill-tertiary-shadow-dark), 0 8px 12px -8px var(--ui-fill-tertiary-shadow-dark)",
      "xs-accent-dark": "0 1px 1px 0 var(--ui-fill-accent-shadow-dark)",
      "sm-accent-dark": "0 2px 5px -1px var(--ui-fill-accent-shadow-dark), 0 1px 2px -1px var(--ui-fill-accent-shadow-dark)",
      "md-accent-dark": "0 5px 10px -2px var(--ui-fill-accent-shadow-dark), 0 2px 4px -2px var(--ui-fill-accent-shadow-dark)",
      "lg-accent-dark": "0 12px 18px -4px var(--ui-fill-accent-shadow-dark), 0 4px 6px -4px var(--ui-fill-accent-shadow-dark)",
      "xl-accent-dark": "0 22px 30px -6px var(--ui-fill-accent-shadow-dark), 0 8px 12px -8px var(--ui-fill-accent-shadow-dark)",
      "xs-muted-dark": "0 1px 1px 0 var(--ui-fill-muted-shadow-dark)",
      "sm-muted-dark": "0 2px 5px -1px var(--ui-fill-muted-shadow-dark), 0 1px 2px -1px var(--ui-fill-muted-shadow-dark)",
      "md-muted-dark": "0 5px 10px -2px var(--ui-fill-muted-shadow-dark), 0 2px 4px -2px var(--ui-fill-muted-shadow-dark)",
      "lg-muted-dark": "0 12px 18px -4px var(--ui-fill-muted-shadow-dark), 0 4px 6px -4px var(--ui-fill-muted-shadow-dark)",
      "xl-muted-dark": "0 22px 30px -6px var(--ui-fill-muted-shadow-dark), 0 8px 12px -8px var(--ui-fill-muted-shadow-dark)",
      "xs-input-dark": "0 1px 1px 0 var(--ui-fill-input-shadow-dark)",
      "sm-input-dark": "0 2px 5px -1px var(--ui-fill-input-shadow-dark), 0 1px 2px -1px var(--ui-fill-input-shadow-dark)",
      "md-input-dark": "0 5px 10px -2px var(--ui-fill-input-shadow-dark), 0 2px 4px -2px var(--ui-fill-input-shadow-dark)",
      "lg-input-dark": "0 12px 18px -4px var(--ui-fill-input-shadow-dark), 0 4px 6px -4px var(--ui-fill-input-shadow-dark)",
      "xl-input-dark": "0 22px 30px -6px var(--ui-fill-input-shadow-dark), 0 8px 12px -8px var(--ui-fill-input-shadow-dark)",
      "xs-link-dark": "0 1px 1px 0 var(--ui-fill-link-shadow-dark)",
      "sm-link-dark": "0 2px 5px -1px var(--ui-fill-link-shadow-dark), 0 1px 2px -1px var(--ui-fill-link-shadow-dark)",
      "md-link-dark": "0 5px 10px -2px var(--ui-fill-link-shadow-dark), 0 2px 4px -2px var(--ui-fill-link-shadow-dark)",
      "lg-link-dark": "0 12px 18px -4px var(--ui-fill-link-shadow-dark), 0 4px 6px -4px var(--ui-fill-link-shadow-dark)",
      "xl-link-dark": "0 22px 30px -6px var(--ui-fill-link-shadow-dark), 0 8px 12px -8px var(--ui-fill-link-shadow-dark)",
      "xs-success-dark": "0 1px 1px 0 var(--ui-fill-success-shadow-dark)",
      "sm-success-dark": "0 2px 5px -1px var(--ui-fill-success-shadow-dark), 0 1px 2px -1px var(--ui-fill-success-shadow-dark)",
      "md-success-dark": "0 5px 10px -2px var(--ui-fill-success-shadow-dark), 0 2px 4px -2px var(--ui-fill-success-shadow-dark)",
      "lg-success-dark": "0 12px 18px -4px var(--ui-fill-success-shadow-dark), 0 4px 6px -4px var(--ui-fill-success-shadow-dark)",
      "xl-success-dark": "0 22px 30px -6px var(--ui-fill-success-shadow-dark), 0 8px 12px -8px var(--ui-fill-success-shadow-dark)",
      "xs-info-dark": "0 1px 1px 0 var(--ui-fill-info-shadow-dark)",
      "sm-info-dark": "0 2px 5px -1px var(--ui-fill-info-shadow-dark), 0 1px 2px -1px var(--ui-fill-info-shadow-dark)",
      "md-info-dark": "0 5px 10px -2px var(--ui-fill-info-shadow-dark), 0 2px 4px -2px var(--ui-fill-info-shadow-dark)",
      "lg-info-dark": "0 12px 18px -4px var(--ui-fill-info-shadow-dark), 0 4px 6px -4px var(--ui-fill-info-shadow-dark)",
      "xl-info-dark": "0 22px 30px -6px var(--ui-fill-info-shadow-dark), 0 8px 12px -8px var(--ui-fill-info-shadow-dark)",
      "xs-warning-dark": "0 1px 1px 0 var(--ui-fill-warning-shadow-dark)",
      "sm-warning-dark": "0 2px 5px -1px var(--ui-fill-warning-shadow-dark), 0 1px 2px -1px var(--ui-fill-warning-shadow-dark)",
      "md-warning-dark": "0 5px 10px -2px var(--ui-fill-warning-shadow-dark), 0 2px 4px -2px var(--ui-fill-warning-shadow-dark)",
      "lg-warning-dark": "0 12px 18px -4px var(--ui-fill-warning-shadow-dark), 0 4px 6px -4px var(--ui-fill-warning-shadow-dark)",
      "xl-warning-dark": "0 22px 30px -6px var(--ui-fill-warning-shadow-dark), 0 8px 12px -8px var(--ui-fill-warning-shadow-dark)",
      "xs-error-dark": "0 1px 1px 0 var(--ui-fill-error-shadow-dark)",
      "sm-error-dark": "0 2px 5px -1px var(--ui-fill-error-shadow-dark), 0 1px 2px -1px var(--ui-fill-error-shadow-dark)",
      "md-error-dark": "0 5px 10px -2px var(--ui-fill-error-shadow-dark), 0 2px 4px -2px var(--ui-fill-error-shadow-dark)",
      "lg-error-dark": "0 12px 18px -4px var(--ui-fill-error-shadow-dark), 0 4px 6px -4px var(--ui-fill-error-shadow-dark)",
      "xl-error-dark": "0 22px 30px -6px var(--ui-fill-error-shadow-dark), 0 8px 12px -8px var(--ui-fill-error-shadow-dark)",
      "xs-notification-dark": "0 1px 1px 0 var(--ui-fill-notification-shadow-dark)",
      "sm-notification-dark": "0 2px 5px -1px var(--ui-fill-notification-shadow-dark), 0 1px 2px -1px var(--ui-fill-notification-shadow-dark)",
      "md-notification-dark": "0 5px 10px -2px var(--ui-fill-notification-shadow-dark), 0 2px 4px -2px var(--ui-fill-notification-shadow-dark)",
      "lg-notification-dark": "0 12px 18px -4px var(--ui-fill-notification-shadow-dark), 0 4px 6px -4px var(--ui-fill-notification-shadow-dark)",
      "xl-notification-dark": "0 22px 30px -6px var(--ui-fill-notification-shadow-dark), 0 8px 12px -8px var(--ui-fill-notification-shadow-dark)"
    },
    "insetShadow": {
      "xs-light": "var(--ui-inset-shadow-xs-base-light)",
      "sm-light": "var(--ui-inset-shadow-sm-base-light)",
      "md-light": "var(--ui-inset-shadow-md-base-light)",
      "lg-light": "var(--ui-inset-shadow-lg-base-light)",
      "xl-light": "var(--ui-inset-shadow-xl-base-light)",
      "xs-floor-light": "inset 0 1px 1px 0 var(--ui-fill-floor-shadow-light)",
      "sm-floor-light": "inset 0 2px 4px 0 var(--ui-fill-floor-shadow-light)",
      "md-floor-light": "inset 0 3px 7px 0 var(--ui-fill-floor-shadow-light)",
      "lg-floor-light": "inset 0 5px 11px 0 var(--ui-fill-floor-shadow-light)",
      "xl-floor-light": "inset 0 8px 16px 0 var(--ui-fill-floor-shadow-light)",
      "xs-base-light": "inset 0 1px 1px 0 var(--ui-fill-base-shadow-light)",
      "sm-base-light": "inset 0 2px 4px 0 var(--ui-fill-base-shadow-light)",
      "md-base-light": "inset 0 3px 7px 0 var(--ui-fill-base-shadow-light)",
      "lg-base-light": "inset 0 5px 11px 0 var(--ui-fill-base-shadow-light)",
      "xl-base-light": "inset 0 8px 16px 0 var(--ui-fill-base-shadow-light)",
      "xs-primary-light": "inset 0 1px 1px 0 var(--ui-fill-primary-shadow-light)",
      "sm-primary-light": "inset 0 2px 4px 0 var(--ui-fill-primary-shadow-light)",
      "md-primary-light": "inset 0 3px 7px 0 var(--ui-fill-primary-shadow-light)",
      "lg-primary-light": "inset 0 5px 11px 0 var(--ui-fill-primary-shadow-light)",
      "xl-primary-light": "inset 0 8px 16px 0 var(--ui-fill-primary-shadow-light)",
      "xs-secondary-light": "inset 0 1px 1px 0 var(--ui-fill-secondary-shadow-light)",
      "sm-secondary-light": "inset 0 2px 4px 0 var(--ui-fill-secondary-shadow-light)",
      "md-secondary-light": "inset 0 3px 7px 0 var(--ui-fill-secondary-shadow-light)",
      "lg-secondary-light": "inset 0 5px 11px 0 var(--ui-fill-secondary-shadow-light)",
      "xl-secondary-light": "inset 0 8px 16px 0 var(--ui-fill-secondary-shadow-light)",
      "xs-tertiary-light": "inset 0 1px 1px 0 var(--ui-fill-tertiary-shadow-light)",
      "sm-tertiary-light": "inset 0 2px 4px 0 var(--ui-fill-tertiary-shadow-light)",
      "md-tertiary-light": "inset 0 3px 7px 0 var(--ui-fill-tertiary-shadow-light)",
      "lg-tertiary-light": "inset 0 5px 11px 0 var(--ui-fill-tertiary-shadow-light)",
      "xl-tertiary-light": "inset 0 8px 16px 0 var(--ui-fill-tertiary-shadow-light)",
      "xs-accent-light": "inset 0 1px 1px 0 var(--ui-fill-accent-shadow-light)",
      "sm-accent-light": "inset 0 2px 4px 0 var(--ui-fill-accent-shadow-light)",
      "md-accent-light": "inset 0 3px 7px 0 var(--ui-fill-accent-shadow-light)",
      "lg-accent-light": "inset 0 5px 11px 0 var(--ui-fill-accent-shadow-light)",
      "xl-accent-light": "inset 0 8px 16px 0 var(--ui-fill-accent-shadow-light)",
      "xs-muted-light": "inset 0 1px 1px 0 var(--ui-fill-muted-shadow-light)",
      "sm-muted-light": "inset 0 2px 4px 0 var(--ui-fill-muted-shadow-light)",
      "md-muted-light": "inset 0 3px 7px 0 var(--ui-fill-muted-shadow-light)",
      "lg-muted-light": "inset 0 5px 11px 0 var(--ui-fill-muted-shadow-light)",
      "xl-muted-light": "inset 0 8px 16px 0 var(--ui-fill-muted-shadow-light)",
      "xs-input-light": "inset 0 1px 1px 0 var(--ui-fill-input-shadow-light)",
      "sm-input-light": "inset 0 2px 4px 0 var(--ui-fill-input-shadow-light)",
      "md-input-light": "inset 0 3px 7px 0 var(--ui-fill-input-shadow-light)",
      "lg-input-light": "inset 0 5px 11px 0 var(--ui-fill-input-shadow-light)",
      "xl-input-light": "inset 0 8px 16px 0 var(--ui-fill-input-shadow-light)",
      "xs-link-light": "inset 0 1px 1px 0 var(--ui-fill-link-shadow-light)",
      "sm-link-light": "inset 0 2px 4px 0 var(--ui-fill-link-shadow-light)",
      "md-link-light": "inset 0 3px 7px 0 var(--ui-fill-link-shadow-light)",
      "lg-link-light": "inset 0 5px 11px 0 var(--ui-fill-link-shadow-light)",
      "xl-link-light": "inset 0 8px 16px 0 var(--ui-fill-link-shadow-light)",
      "xs-success-light": "inset 0 1px 1px 0 var(--ui-fill-success-shadow-light)",
      "sm-success-light": "inset 0 2px 4px 0 var(--ui-fill-success-shadow-light)",
      "md-success-light": "inset 0 3px 7px 0 var(--ui-fill-success-shadow-light)",
      "lg-success-light": "inset 0 5px 11px 0 var(--ui-fill-success-shadow-light)",
      "xl-success-light": "inset 0 8px 16px 0 var(--ui-fill-success-shadow-light)",
      "xs-info-light": "inset 0 1px 1px 0 var(--ui-fill-info-shadow-light)",
      "sm-info-light": "inset 0 2px 4px 0 var(--ui-fill-info-shadow-light)",
      "md-info-light": "inset 0 3px 7px 0 var(--ui-fill-info-shadow-light)",
      "lg-info-light": "inset 0 5px 11px 0 var(--ui-fill-info-shadow-light)",
      "xl-info-light": "inset 0 8px 16px 0 var(--ui-fill-info-shadow-light)",
      "xs-warning-light": "inset 0 1px 1px 0 var(--ui-fill-warning-shadow-light)",
      "sm-warning-light": "inset 0 2px 4px 0 var(--ui-fill-warning-shadow-light)",
      "md-warning-light": "inset 0 3px 7px 0 var(--ui-fill-warning-shadow-light)",
      "lg-warning-light": "inset 0 5px 11px 0 var(--ui-fill-warning-shadow-light)",
      "xl-warning-light": "inset 0 8px 16px 0 var(--ui-fill-warning-shadow-light)",
      "xs-error-light": "inset 0 1px 1px 0 var(--ui-fill-error-shadow-light)",
      "sm-error-light": "inset 0 2px 4px 0 var(--ui-fill-error-shadow-light)",
      "md-error-light": "inset 0 3px 7px 0 var(--ui-fill-error-shadow-light)",
      "lg-error-light": "inset 0 5px 11px 0 var(--ui-fill-error-shadow-light)",
      "xl-error-light": "inset 0 8px 16px 0 var(--ui-fill-error-shadow-light)",
      "xs-notification-light": "inset 0 1px 1px 0 var(--ui-fill-notification-shadow-light)",
      "sm-notification-light": "inset 0 2px 4px 0 var(--ui-fill-notification-shadow-light)",
      "md-notification-light": "inset 0 3px 7px 0 var(--ui-fill-notification-shadow-light)",
      "lg-notification-light": "inset 0 5px 11px 0 var(--ui-fill-notification-shadow-light)",
      "xl-notification-light": "inset 0 8px 16px 0 var(--ui-fill-notification-shadow-light)",
      "xs-dark": "var(--ui-inset-shadow-xs-base-dark)",
      "sm-dark": "var(--ui-inset-shadow-sm-base-dark)",
      "md-dark": "var(--ui-inset-shadow-md-base-dark)",
      "lg-dark": "var(--ui-inset-shadow-lg-base-dark)",
      "xl-dark": "var(--ui-inset-shadow-xl-base-dark)",
      "xs-floor-dark": "inset 0 1px 1px 0 var(--ui-fill-floor-shadow-dark)",
      "sm-floor-dark": "inset 0 2px 4px 0 var(--ui-fill-floor-shadow-dark)",
      "md-floor-dark": "inset 0 3px 7px 0 var(--ui-fill-floor-shadow-dark)",
      "lg-floor-dark": "inset 0 5px 11px 0 var(--ui-fill-floor-shadow-dark)",
      "xl-floor-dark": "inset 0 8px 16px 0 var(--ui-fill-floor-shadow-dark)",
      "xs-base-dark": "inset 0 1px 1px 0 var(--ui-fill-base-shadow-dark)",
      "sm-base-dark": "inset 0 2px 4px 0 var(--ui-fill-base-shadow-dark)",
      "md-base-dark": "inset 0 3px 7px 0 var(--ui-fill-base-shadow-dark)",
      "lg-base-dark": "inset 0 5px 11px 0 var(--ui-fill-base-shadow-dark)",
      "xl-base-dark": "inset 0 8px 16px 0 var(--ui-fill-base-shadow-dark)",
      "xs-primary-dark": "inset 0 1px 1px 0 var(--ui-fill-primary-shadow-dark)",
      "sm-primary-dark": "inset 0 2px 4px 0 var(--ui-fill-primary-shadow-dark)",
      "md-primary-dark": "inset 0 3px 7px 0 var(--ui-fill-primary-shadow-dark)",
      "lg-primary-dark": "inset 0 5px 11px 0 var(--ui-fill-primary-shadow-dark)",
      "xl-primary-dark": "inset 0 8px 16px 0 var(--ui-fill-primary-shadow-dark)",
      "xs-secondary-dark": "inset 0 1px 1px 0 var(--ui-fill-secondary-shadow-dark)",
      "sm-secondary-dark": "inset 0 2px 4px 0 var(--ui-fill-secondary-shadow-dark)",
      "md-secondary-dark": "inset 0 3px 7px 0 var(--ui-fill-secondary-shadow-dark)",
      "lg-secondary-dark": "inset 0 5px 11px 0 var(--ui-fill-secondary-shadow-dark)",
      "xl-secondary-dark": "inset 0 8px 16px 0 var(--ui-fill-secondary-shadow-dark)",
      "xs-tertiary-dark": "inset 0 1px 1px 0 var(--ui-fill-tertiary-shadow-dark)",
      "sm-tertiary-dark": "inset 0 2px 4px 0 var(--ui-fill-tertiary-shadow-dark)",
      "md-tertiary-dark": "inset 0 3px 7px 0 var(--ui-fill-tertiary-shadow-dark)",
      "lg-tertiary-dark": "inset 0 5px 11px 0 var(--ui-fill-tertiary-shadow-dark)",
      "xl-tertiary-dark": "inset 0 8px 16px 0 var(--ui-fill-tertiary-shadow-dark)",
      "xs-accent-dark": "inset 0 1px 1px 0 var(--ui-fill-accent-shadow-dark)",
      "sm-accent-dark": "inset 0 2px 4px 0 var(--ui-fill-accent-shadow-dark)",
      "md-accent-dark": "inset 0 3px 7px 0 var(--ui-fill-accent-shadow-dark)",
      "lg-accent-dark": "inset 0 5px 11px 0 var(--ui-fill-accent-shadow-dark)",
      "xl-accent-dark": "inset 0 8px 16px 0 var(--ui-fill-accent-shadow-dark)",
      "xs-muted-dark": "inset 0 1px 1px 0 var(--ui-fill-muted-shadow-dark)",
      "sm-muted-dark": "inset 0 2px 4px 0 var(--ui-fill-muted-shadow-dark)",
      "md-muted-dark": "inset 0 3px 7px 0 var(--ui-fill-muted-shadow-dark)",
      "lg-muted-dark": "inset 0 5px 11px 0 var(--ui-fill-muted-shadow-dark)",
      "xl-muted-dark": "inset 0 8px 16px 0 var(--ui-fill-muted-shadow-dark)",
      "xs-input-dark": "inset 0 1px 1px 0 var(--ui-fill-input-shadow-dark)",
      "sm-input-dark": "inset 0 2px 4px 0 var(--ui-fill-input-shadow-dark)",
      "md-input-dark": "inset 0 3px 7px 0 var(--ui-fill-input-shadow-dark)",
      "lg-input-dark": "inset 0 5px 11px 0 var(--ui-fill-input-shadow-dark)",
      "xl-input-dark": "inset 0 8px 16px 0 var(--ui-fill-input-shadow-dark)",
      "xs-link-dark": "inset 0 1px 1px 0 var(--ui-fill-link-shadow-dark)",
      "sm-link-dark": "inset 0 2px 4px 0 var(--ui-fill-link-shadow-dark)",
      "md-link-dark": "inset 0 3px 7px 0 var(--ui-fill-link-shadow-dark)",
      "lg-link-dark": "inset 0 5px 11px 0 var(--ui-fill-link-shadow-dark)",
      "xl-link-dark": "inset 0 8px 16px 0 var(--ui-fill-link-shadow-dark)",
      "xs-success-dark": "inset 0 1px 1px 0 var(--ui-fill-success-shadow-dark)",
      "sm-success-dark": "inset 0 2px 4px 0 var(--ui-fill-success-shadow-dark)",
      "md-success-dark": "inset 0 3px 7px 0 var(--ui-fill-success-shadow-dark)",
      "lg-success-dark": "inset 0 5px 11px 0 var(--ui-fill-success-shadow-dark)",
      "xl-success-dark": "inset 0 8px 16px 0 var(--ui-fill-success-shadow-dark)",
      "xs-info-dark": "inset 0 1px 1px 0 var(--ui-fill-info-shadow-dark)",
      "sm-info-dark": "inset 0 2px 4px 0 var(--ui-fill-info-shadow-dark)",
      "md-info-dark": "inset 0 3px 7px 0 var(--ui-fill-info-shadow-dark)",
      "lg-info-dark": "inset 0 5px 11px 0 var(--ui-fill-info-shadow-dark)",
      "xl-info-dark": "inset 0 8px 16px 0 var(--ui-fill-info-shadow-dark)",
      "xs-warning-dark": "inset 0 1px 1px 0 var(--ui-fill-warning-shadow-dark)",
      "sm-warning-dark": "inset 0 2px 4px 0 var(--ui-fill-warning-shadow-dark)",
      "md-warning-dark": "inset 0 3px 7px 0 var(--ui-fill-warning-shadow-dark)",
      "lg-warning-dark": "inset 0 5px 11px 0 var(--ui-fill-warning-shadow-dark)",
      "xl-warning-dark": "inset 0 8px 16px 0 var(--ui-fill-warning-shadow-dark)",
      "xs-error-dark": "inset 0 1px 1px 0 var(--ui-fill-error-shadow-dark)",
      "sm-error-dark": "inset 0 2px 4px 0 var(--ui-fill-error-shadow-dark)",
      "md-error-dark": "inset 0 3px 7px 0 var(--ui-fill-error-shadow-dark)",
      "lg-error-dark": "inset 0 5px 11px 0 var(--ui-fill-error-shadow-dark)",
      "xl-error-dark": "inset 0 8px 16px 0 var(--ui-fill-error-shadow-dark)",
      "xs-notification-dark": "inset 0 1px 1px 0 var(--ui-fill-notification-shadow-dark)",
      "sm-notification-dark": "inset 0 2px 4px 0 var(--ui-fill-notification-shadow-dark)",
      "md-notification-dark": "inset 0 3px 7px 0 var(--ui-fill-notification-shadow-dark)",
      "lg-notification-dark": "inset 0 5px 11px 0 var(--ui-fill-notification-shadow-dark)",
      "xl-notification-dark": "inset 0 8px 16px 0 var(--ui-fill-notification-shadow-dark)"
    },
    "dropShadow": {
      "xs-light": "var(--ui-drop-shadow-xs-base-light)",
      "sm-light": "var(--ui-drop-shadow-sm-base-light)",
      "md-light": "var(--ui-drop-shadow-md-base-light)",
      "lg-light": "var(--ui-drop-shadow-lg-base-light)",
      "xl-light": "var(--ui-drop-shadow-xl-base-light)",
      "xs-floor-light": "0 1px 1px var(--ui-fill-floor-shadow-light)",
      "sm-floor-light": "0 2px 3px var(--ui-fill-floor-shadow-light)",
      "md-floor-light": "0 4px 6px var(--ui-fill-floor-shadow-light)",
      "lg-floor-light": "0 10px 10px var(--ui-fill-floor-shadow-light)",
      "xl-floor-light": "0 20px 16px var(--ui-fill-floor-shadow-light)",
      "xs-base-light": "0 1px 1px var(--ui-fill-base-shadow-light)",
      "sm-base-light": "0 2px 3px var(--ui-fill-base-shadow-light)",
      "md-base-light": "0 4px 6px var(--ui-fill-base-shadow-light)",
      "lg-base-light": "0 10px 10px var(--ui-fill-base-shadow-light)",
      "xl-base-light": "0 20px 16px var(--ui-fill-base-shadow-light)",
      "xs-primary-light": "0 1px 1px var(--ui-fill-primary-shadow-light)",
      "sm-primary-light": "0 2px 3px var(--ui-fill-primary-shadow-light)",
      "md-primary-light": "0 4px 6px var(--ui-fill-primary-shadow-light)",
      "lg-primary-light": "0 10px 10px var(--ui-fill-primary-shadow-light)",
      "xl-primary-light": "0 20px 16px var(--ui-fill-primary-shadow-light)",
      "xs-secondary-light": "0 1px 1px var(--ui-fill-secondary-shadow-light)",
      "sm-secondary-light": "0 2px 3px var(--ui-fill-secondary-shadow-light)",
      "md-secondary-light": "0 4px 6px var(--ui-fill-secondary-shadow-light)",
      "lg-secondary-light": "0 10px 10px var(--ui-fill-secondary-shadow-light)",
      "xl-secondary-light": "0 20px 16px var(--ui-fill-secondary-shadow-light)",
      "xs-tertiary-light": "0 1px 1px var(--ui-fill-tertiary-shadow-light)",
      "sm-tertiary-light": "0 2px 3px var(--ui-fill-tertiary-shadow-light)",
      "md-tertiary-light": "0 4px 6px var(--ui-fill-tertiary-shadow-light)",
      "lg-tertiary-light": "0 10px 10px var(--ui-fill-tertiary-shadow-light)",
      "xl-tertiary-light": "0 20px 16px var(--ui-fill-tertiary-shadow-light)",
      "xs-accent-light": "0 1px 1px var(--ui-fill-accent-shadow-light)",
      "sm-accent-light": "0 2px 3px var(--ui-fill-accent-shadow-light)",
      "md-accent-light": "0 4px 6px var(--ui-fill-accent-shadow-light)",
      "lg-accent-light": "0 10px 10px var(--ui-fill-accent-shadow-light)",
      "xl-accent-light": "0 20px 16px var(--ui-fill-accent-shadow-light)",
      "xs-muted-light": "0 1px 1px var(--ui-fill-muted-shadow-light)",
      "sm-muted-light": "0 2px 3px var(--ui-fill-muted-shadow-light)",
      "md-muted-light": "0 4px 6px var(--ui-fill-muted-shadow-light)",
      "lg-muted-light": "0 10px 10px var(--ui-fill-muted-shadow-light)",
      "xl-muted-light": "0 20px 16px var(--ui-fill-muted-shadow-light)",
      "xs-input-light": "0 1px 1px var(--ui-fill-input-shadow-light)",
      "sm-input-light": "0 2px 3px var(--ui-fill-input-shadow-light)",
      "md-input-light": "0 4px 6px var(--ui-fill-input-shadow-light)",
      "lg-input-light": "0 10px 10px var(--ui-fill-input-shadow-light)",
      "xl-input-light": "0 20px 16px var(--ui-fill-input-shadow-light)",
      "xs-link-light": "0 1px 1px var(--ui-fill-link-shadow-light)",
      "sm-link-light": "0 2px 3px var(--ui-fill-link-shadow-light)",
      "md-link-light": "0 4px 6px var(--ui-fill-link-shadow-light)",
      "lg-link-light": "0 10px 10px var(--ui-fill-link-shadow-light)",
      "xl-link-light": "0 20px 16px var(--ui-fill-link-shadow-light)",
      "xs-success-light": "0 1px 1px var(--ui-fill-success-shadow-light)",
      "sm-success-light": "0 2px 3px var(--ui-fill-success-shadow-light)",
      "md-success-light": "0 4px 6px var(--ui-fill-success-shadow-light)",
      "lg-success-light": "0 10px 10px var(--ui-fill-success-shadow-light)",
      "xl-success-light": "0 20px 16px var(--ui-fill-success-shadow-light)",
      "xs-info-light": "0 1px 1px var(--ui-fill-info-shadow-light)",
      "sm-info-light": "0 2px 3px var(--ui-fill-info-shadow-light)",
      "md-info-light": "0 4px 6px var(--ui-fill-info-shadow-light)",
      "lg-info-light": "0 10px 10px var(--ui-fill-info-shadow-light)",
      "xl-info-light": "0 20px 16px var(--ui-fill-info-shadow-light)",
      "xs-warning-light": "0 1px 1px var(--ui-fill-warning-shadow-light)",
      "sm-warning-light": "0 2px 3px var(--ui-fill-warning-shadow-light)",
      "md-warning-light": "0 4px 6px var(--ui-fill-warning-shadow-light)",
      "lg-warning-light": "0 10px 10px var(--ui-fill-warning-shadow-light)",
      "xl-warning-light": "0 20px 16px var(--ui-fill-warning-shadow-light)",
      "xs-error-light": "0 1px 1px var(--ui-fill-error-shadow-light)",
      "sm-error-light": "0 2px 3px var(--ui-fill-error-shadow-light)",
      "md-error-light": "0 4px 6px var(--ui-fill-error-shadow-light)",
      "lg-error-light": "0 10px 10px var(--ui-fill-error-shadow-light)",
      "xl-error-light": "0 20px 16px var(--ui-fill-error-shadow-light)",
      "xs-notification-light": "0 1px 1px var(--ui-fill-notification-shadow-light)",
      "sm-notification-light": "0 2px 3px var(--ui-fill-notification-shadow-light)",
      "md-notification-light": "0 4px 6px var(--ui-fill-notification-shadow-light)",
      "lg-notification-light": "0 10px 10px var(--ui-fill-notification-shadow-light)",
      "xl-notification-light": "0 20px 16px var(--ui-fill-notification-shadow-light)",
      "xs-dark": "var(--ui-drop-shadow-xs-base-dark)",
      "sm-dark": "var(--ui-drop-shadow-sm-base-dark)",
      "md-dark": "var(--ui-drop-shadow-md-base-dark)",
      "lg-dark": "var(--ui-drop-shadow-lg-base-dark)",
      "xl-dark": "var(--ui-drop-shadow-xl-base-dark)",
      "xs-floor-dark": "0 1px 1px var(--ui-fill-floor-shadow-dark)",
      "sm-floor-dark": "0 2px 3px var(--ui-fill-floor-shadow-dark)",
      "md-floor-dark": "0 4px 6px var(--ui-fill-floor-shadow-dark)",
      "lg-floor-dark": "0 10px 10px var(--ui-fill-floor-shadow-dark)",
      "xl-floor-dark": "0 20px 16px var(--ui-fill-floor-shadow-dark)",
      "xs-base-dark": "0 1px 1px var(--ui-fill-base-shadow-dark)",
      "sm-base-dark": "0 2px 3px var(--ui-fill-base-shadow-dark)",
      "md-base-dark": "0 4px 6px var(--ui-fill-base-shadow-dark)",
      "lg-base-dark": "0 10px 10px var(--ui-fill-base-shadow-dark)",
      "xl-base-dark": "0 20px 16px var(--ui-fill-base-shadow-dark)",
      "xs-primary-dark": "0 1px 1px var(--ui-fill-primary-shadow-dark)",
      "sm-primary-dark": "0 2px 3px var(--ui-fill-primary-shadow-dark)",
      "md-primary-dark": "0 4px 6px var(--ui-fill-primary-shadow-dark)",
      "lg-primary-dark": "0 10px 10px var(--ui-fill-primary-shadow-dark)",
      "xl-primary-dark": "0 20px 16px var(--ui-fill-primary-shadow-dark)",
      "xs-secondary-dark": "0 1px 1px var(--ui-fill-secondary-shadow-dark)",
      "sm-secondary-dark": "0 2px 3px var(--ui-fill-secondary-shadow-dark)",
      "md-secondary-dark": "0 4px 6px var(--ui-fill-secondary-shadow-dark)",
      "lg-secondary-dark": "0 10px 10px var(--ui-fill-secondary-shadow-dark)",
      "xl-secondary-dark": "0 20px 16px var(--ui-fill-secondary-shadow-dark)",
      "xs-tertiary-dark": "0 1px 1px var(--ui-fill-tertiary-shadow-dark)",
      "sm-tertiary-dark": "0 2px 3px var(--ui-fill-tertiary-shadow-dark)",
      "md-tertiary-dark": "0 4px 6px var(--ui-fill-tertiary-shadow-dark)",
      "lg-tertiary-dark": "0 10px 10px var(--ui-fill-tertiary-shadow-dark)",
      "xl-tertiary-dark": "0 20px 16px var(--ui-fill-tertiary-shadow-dark)",
      "xs-accent-dark": "0 1px 1px var(--ui-fill-accent-shadow-dark)",
      "sm-accent-dark": "0 2px 3px var(--ui-fill-accent-shadow-dark)",
      "md-accent-dark": "0 4px 6px var(--ui-fill-accent-shadow-dark)",
      "lg-accent-dark": "0 10px 10px var(--ui-fill-accent-shadow-dark)",
      "xl-accent-dark": "0 20px 16px var(--ui-fill-accent-shadow-dark)",
      "xs-muted-dark": "0 1px 1px var(--ui-fill-muted-shadow-dark)",
      "sm-muted-dark": "0 2px 3px var(--ui-fill-muted-shadow-dark)",
      "md-muted-dark": "0 4px 6px var(--ui-fill-muted-shadow-dark)",
      "lg-muted-dark": "0 10px 10px var(--ui-fill-muted-shadow-dark)",
      "xl-muted-dark": "0 20px 16px var(--ui-fill-muted-shadow-dark)",
      "xs-input-dark": "0 1px 1px var(--ui-fill-input-shadow-dark)",
      "sm-input-dark": "0 2px 3px var(--ui-fill-input-shadow-dark)",
      "md-input-dark": "0 4px 6px var(--ui-fill-input-shadow-dark)",
      "lg-input-dark": "0 10px 10px var(--ui-fill-input-shadow-dark)",
      "xl-input-dark": "0 20px 16px var(--ui-fill-input-shadow-dark)",
      "xs-link-dark": "0 1px 1px var(--ui-fill-link-shadow-dark)",
      "sm-link-dark": "0 2px 3px var(--ui-fill-link-shadow-dark)",
      "md-link-dark": "0 4px 6px var(--ui-fill-link-shadow-dark)",
      "lg-link-dark": "0 10px 10px var(--ui-fill-link-shadow-dark)",
      "xl-link-dark": "0 20px 16px var(--ui-fill-link-shadow-dark)",
      "xs-success-dark": "0 1px 1px var(--ui-fill-success-shadow-dark)",
      "sm-success-dark": "0 2px 3px var(--ui-fill-success-shadow-dark)",
      "md-success-dark": "0 4px 6px var(--ui-fill-success-shadow-dark)",
      "lg-success-dark": "0 10px 10px var(--ui-fill-success-shadow-dark)",
      "xl-success-dark": "0 20px 16px var(--ui-fill-success-shadow-dark)",
      "xs-info-dark": "0 1px 1px var(--ui-fill-info-shadow-dark)",
      "sm-info-dark": "0 2px 3px var(--ui-fill-info-shadow-dark)",
      "md-info-dark": "0 4px 6px var(--ui-fill-info-shadow-dark)",
      "lg-info-dark": "0 10px 10px var(--ui-fill-info-shadow-dark)",
      "xl-info-dark": "0 20px 16px var(--ui-fill-info-shadow-dark)",
      "xs-warning-dark": "0 1px 1px var(--ui-fill-warning-shadow-dark)",
      "sm-warning-dark": "0 2px 3px var(--ui-fill-warning-shadow-dark)",
      "md-warning-dark": "0 4px 6px var(--ui-fill-warning-shadow-dark)",
      "lg-warning-dark": "0 10px 10px var(--ui-fill-warning-shadow-dark)",
      "xl-warning-dark": "0 20px 16px var(--ui-fill-warning-shadow-dark)",
      "xs-error-dark": "0 1px 1px var(--ui-fill-error-shadow-dark)",
      "sm-error-dark": "0 2px 3px var(--ui-fill-error-shadow-dark)",
      "md-error-dark": "0 4px 6px var(--ui-fill-error-shadow-dark)",
      "lg-error-dark": "0 10px 10px var(--ui-fill-error-shadow-dark)",
      "xl-error-dark": "0 20px 16px var(--ui-fill-error-shadow-dark)",
      "xs-notification-dark": "0 1px 1px var(--ui-fill-notification-shadow-dark)",
      "sm-notification-dark": "0 2px 3px var(--ui-fill-notification-shadow-dark)",
      "md-notification-dark": "0 4px 6px var(--ui-fill-notification-shadow-dark)",
      "lg-notification-dark": "0 10px 10px var(--ui-fill-notification-shadow-dark)",
      "xl-notification-dark": "0 20px 16px var(--ui-fill-notification-shadow-dark)"
    },
    "textShadow": {
      "xs-light": "var(--ui-text-shadow-xs-base-light)",
      "sm-light": "var(--ui-text-shadow-sm-base-light)",
      "md-light": "var(--ui-text-shadow-md-base-light)",
      "lg-light": "var(--ui-text-shadow-lg-base-light)",
      "xl-light": "var(--ui-text-shadow-xl-base-light)",
      "xs-floor-light": "0 1px 1px var(--ui-pen-floor-shadow-light)",
      "sm-floor-light": "0 1px 3px var(--ui-pen-floor-shadow-light)",
      "md-floor-light": "0 2px 6px var(--ui-pen-floor-shadow-light)",
      "lg-floor-light": "0 4px 10px var(--ui-pen-floor-shadow-light)",
      "xl-floor-light": "0 6px 16px var(--ui-pen-floor-shadow-light)",
      "xs-base-light": "0 1px 1px var(--ui-pen-base-shadow-light)",
      "sm-base-light": "0 1px 3px var(--ui-pen-base-shadow-light)",
      "md-base-light": "0 2px 6px var(--ui-pen-base-shadow-light)",
      "lg-base-light": "0 4px 10px var(--ui-pen-base-shadow-light)",
      "xl-base-light": "0 6px 16px var(--ui-pen-base-shadow-light)",
      "xs-primary-light": "0 1px 1px var(--ui-pen-primary-shadow-light)",
      "sm-primary-light": "0 1px 3px var(--ui-pen-primary-shadow-light)",
      "md-primary-light": "0 2px 6px var(--ui-pen-primary-shadow-light)",
      "lg-primary-light": "0 4px 10px var(--ui-pen-primary-shadow-light)",
      "xl-primary-light": "0 6px 16px var(--ui-pen-primary-shadow-light)",
      "xs-secondary-light": "0 1px 1px var(--ui-pen-secondary-shadow-light)",
      "sm-secondary-light": "0 1px 3px var(--ui-pen-secondary-shadow-light)",
      "md-secondary-light": "0 2px 6px var(--ui-pen-secondary-shadow-light)",
      "lg-secondary-light": "0 4px 10px var(--ui-pen-secondary-shadow-light)",
      "xl-secondary-light": "0 6px 16px var(--ui-pen-secondary-shadow-light)",
      "xs-tertiary-light": "0 1px 1px var(--ui-pen-tertiary-shadow-light)",
      "sm-tertiary-light": "0 1px 3px var(--ui-pen-tertiary-shadow-light)",
      "md-tertiary-light": "0 2px 6px var(--ui-pen-tertiary-shadow-light)",
      "lg-tertiary-light": "0 4px 10px var(--ui-pen-tertiary-shadow-light)",
      "xl-tertiary-light": "0 6px 16px var(--ui-pen-tertiary-shadow-light)",
      "xs-accent-light": "0 1px 1px var(--ui-pen-accent-shadow-light)",
      "sm-accent-light": "0 1px 3px var(--ui-pen-accent-shadow-light)",
      "md-accent-light": "0 2px 6px var(--ui-pen-accent-shadow-light)",
      "lg-accent-light": "0 4px 10px var(--ui-pen-accent-shadow-light)",
      "xl-accent-light": "0 6px 16px var(--ui-pen-accent-shadow-light)",
      "xs-muted-light": "0 1px 1px var(--ui-pen-muted-shadow-light)",
      "sm-muted-light": "0 1px 3px var(--ui-pen-muted-shadow-light)",
      "md-muted-light": "0 2px 6px var(--ui-pen-muted-shadow-light)",
      "lg-muted-light": "0 4px 10px var(--ui-pen-muted-shadow-light)",
      "xl-muted-light": "0 6px 16px var(--ui-pen-muted-shadow-light)",
      "xs-input-light": "0 1px 1px var(--ui-pen-input-shadow-light)",
      "sm-input-light": "0 1px 3px var(--ui-pen-input-shadow-light)",
      "md-input-light": "0 2px 6px var(--ui-pen-input-shadow-light)",
      "lg-input-light": "0 4px 10px var(--ui-pen-input-shadow-light)",
      "xl-input-light": "0 6px 16px var(--ui-pen-input-shadow-light)",
      "xs-link-light": "0 1px 1px var(--ui-pen-link-shadow-light)",
      "sm-link-light": "0 1px 3px var(--ui-pen-link-shadow-light)",
      "md-link-light": "0 2px 6px var(--ui-pen-link-shadow-light)",
      "lg-link-light": "0 4px 10px var(--ui-pen-link-shadow-light)",
      "xl-link-light": "0 6px 16px var(--ui-pen-link-shadow-light)",
      "xs-success-light": "0 1px 1px var(--ui-pen-success-shadow-light)",
      "sm-success-light": "0 1px 3px var(--ui-pen-success-shadow-light)",
      "md-success-light": "0 2px 6px var(--ui-pen-success-shadow-light)",
      "lg-success-light": "0 4px 10px var(--ui-pen-success-shadow-light)",
      "xl-success-light": "0 6px 16px var(--ui-pen-success-shadow-light)",
      "xs-info-light": "0 1px 1px var(--ui-pen-info-shadow-light)",
      "sm-info-light": "0 1px 3px var(--ui-pen-info-shadow-light)",
      "md-info-light": "0 2px 6px var(--ui-pen-info-shadow-light)",
      "lg-info-light": "0 4px 10px var(--ui-pen-info-shadow-light)",
      "xl-info-light": "0 6px 16px var(--ui-pen-info-shadow-light)",
      "xs-warning-light": "0 1px 1px var(--ui-pen-warning-shadow-light)",
      "sm-warning-light": "0 1px 3px var(--ui-pen-warning-shadow-light)",
      "md-warning-light": "0 2px 6px var(--ui-pen-warning-shadow-light)",
      "lg-warning-light": "0 4px 10px var(--ui-pen-warning-shadow-light)",
      "xl-warning-light": "0 6px 16px var(--ui-pen-warning-shadow-light)",
      "xs-error-light": "0 1px 1px var(--ui-pen-error-shadow-light)",
      "sm-error-light": "0 1px 3px var(--ui-pen-error-shadow-light)",
      "md-error-light": "0 2px 6px var(--ui-pen-error-shadow-light)",
      "lg-error-light": "0 4px 10px var(--ui-pen-error-shadow-light)",
      "xl-error-light": "0 6px 16px var(--ui-pen-error-shadow-light)",
      "xs-notification-light": "0 1px 1px var(--ui-pen-notification-shadow-light)",
      "sm-notification-light": "0 1px 3px var(--ui-pen-notification-shadow-light)",
      "md-notification-light": "0 2px 6px var(--ui-pen-notification-shadow-light)",
      "lg-notification-light": "0 4px 10px var(--ui-pen-notification-shadow-light)",
      "xl-notification-light": "0 6px 16px var(--ui-pen-notification-shadow-light)",
      "xs-dark": "var(--ui-text-shadow-xs-base-dark)",
      "sm-dark": "var(--ui-text-shadow-sm-base-dark)",
      "md-dark": "var(--ui-text-shadow-md-base-dark)",
      "lg-dark": "var(--ui-text-shadow-lg-base-dark)",
      "xl-dark": "var(--ui-text-shadow-xl-base-dark)",
      "xs-floor-dark": "0 1px 1px var(--ui-pen-floor-shadow-dark)",
      "sm-floor-dark": "0 1px 3px var(--ui-pen-floor-shadow-dark)",
      "md-floor-dark": "0 2px 6px var(--ui-pen-floor-shadow-dark)",
      "lg-floor-dark": "0 4px 10px var(--ui-pen-floor-shadow-dark)",
      "xl-floor-dark": "0 6px 16px var(--ui-pen-floor-shadow-dark)",
      "xs-base-dark": "0 1px 1px var(--ui-pen-base-shadow-dark)",
      "sm-base-dark": "0 1px 3px var(--ui-pen-base-shadow-dark)",
      "md-base-dark": "0 2px 6px var(--ui-pen-base-shadow-dark)",
      "lg-base-dark": "0 4px 10px var(--ui-pen-base-shadow-dark)",
      "xl-base-dark": "0 6px 16px var(--ui-pen-base-shadow-dark)",
      "xs-primary-dark": "0 1px 1px var(--ui-pen-primary-shadow-dark)",
      "sm-primary-dark": "0 1px 3px var(--ui-pen-primary-shadow-dark)",
      "md-primary-dark": "0 2px 6px var(--ui-pen-primary-shadow-dark)",
      "lg-primary-dark": "0 4px 10px var(--ui-pen-primary-shadow-dark)",
      "xl-primary-dark": "0 6px 16px var(--ui-pen-primary-shadow-dark)",
      "xs-secondary-dark": "0 1px 1px var(--ui-pen-secondary-shadow-dark)",
      "sm-secondary-dark": "0 1px 3px var(--ui-pen-secondary-shadow-dark)",
      "md-secondary-dark": "0 2px 6px var(--ui-pen-secondary-shadow-dark)",
      "lg-secondary-dark": "0 4px 10px var(--ui-pen-secondary-shadow-dark)",
      "xl-secondary-dark": "0 6px 16px var(--ui-pen-secondary-shadow-dark)",
      "xs-tertiary-dark": "0 1px 1px var(--ui-pen-tertiary-shadow-dark)",
      "sm-tertiary-dark": "0 1px 3px var(--ui-pen-tertiary-shadow-dark)",
      "md-tertiary-dark": "0 2px 6px var(--ui-pen-tertiary-shadow-dark)",
      "lg-tertiary-dark": "0 4px 10px var(--ui-pen-tertiary-shadow-dark)",
      "xl-tertiary-dark": "0 6px 16px var(--ui-pen-tertiary-shadow-dark)",
      "xs-accent-dark": "0 1px 1px var(--ui-pen-accent-shadow-dark)",
      "sm-accent-dark": "0 1px 3px var(--ui-pen-accent-shadow-dark)",
      "md-accent-dark": "0 2px 6px var(--ui-pen-accent-shadow-dark)",
      "lg-accent-dark": "0 4px 10px var(--ui-pen-accent-shadow-dark)",
      "xl-accent-dark": "0 6px 16px var(--ui-pen-accent-shadow-dark)",
      "xs-muted-dark": "0 1px 1px var(--ui-pen-muted-shadow-dark)",
      "sm-muted-dark": "0 1px 3px var(--ui-pen-muted-shadow-dark)",
      "md-muted-dark": "0 2px 6px var(--ui-pen-muted-shadow-dark)",
      "lg-muted-dark": "0 4px 10px var(--ui-pen-muted-shadow-dark)",
      "xl-muted-dark": "0 6px 16px var(--ui-pen-muted-shadow-dark)",
      "xs-input-dark": "0 1px 1px var(--ui-pen-input-shadow-dark)",
      "sm-input-dark": "0 1px 3px var(--ui-pen-input-shadow-dark)",
      "md-input-dark": "0 2px 6px var(--ui-pen-input-shadow-dark)",
      "lg-input-dark": "0 4px 10px var(--ui-pen-input-shadow-dark)",
      "xl-input-dark": "0 6px 16px var(--ui-pen-input-shadow-dark)",
      "xs-link-dark": "0 1px 1px var(--ui-pen-link-shadow-dark)",
      "sm-link-dark": "0 1px 3px var(--ui-pen-link-shadow-dark)",
      "md-link-dark": "0 2px 6px var(--ui-pen-link-shadow-dark)",
      "lg-link-dark": "0 4px 10px var(--ui-pen-link-shadow-dark)",
      "xl-link-dark": "0 6px 16px var(--ui-pen-link-shadow-dark)",
      "xs-success-dark": "0 1px 1px var(--ui-pen-success-shadow-dark)",
      "sm-success-dark": "0 1px 3px var(--ui-pen-success-shadow-dark)",
      "md-success-dark": "0 2px 6px var(--ui-pen-success-shadow-dark)",
      "lg-success-dark": "0 4px 10px var(--ui-pen-success-shadow-dark)",
      "xl-success-dark": "0 6px 16px var(--ui-pen-success-shadow-dark)",
      "xs-info-dark": "0 1px 1px var(--ui-pen-info-shadow-dark)",
      "sm-info-dark": "0 1px 3px var(--ui-pen-info-shadow-dark)",
      "md-info-dark": "0 2px 6px var(--ui-pen-info-shadow-dark)",
      "lg-info-dark": "0 4px 10px var(--ui-pen-info-shadow-dark)",
      "xl-info-dark": "0 6px 16px var(--ui-pen-info-shadow-dark)",
      "xs-warning-dark": "0 1px 1px var(--ui-pen-warning-shadow-dark)",
      "sm-warning-dark": "0 1px 3px var(--ui-pen-warning-shadow-dark)",
      "md-warning-dark": "0 2px 6px var(--ui-pen-warning-shadow-dark)",
      "lg-warning-dark": "0 4px 10px var(--ui-pen-warning-shadow-dark)",
      "xl-warning-dark": "0 6px 16px var(--ui-pen-warning-shadow-dark)",
      "xs-error-dark": "0 1px 1px var(--ui-pen-error-shadow-dark)",
      "sm-error-dark": "0 1px 3px var(--ui-pen-error-shadow-dark)",
      "md-error-dark": "0 2px 6px var(--ui-pen-error-shadow-dark)",
      "lg-error-dark": "0 4px 10px var(--ui-pen-error-shadow-dark)",
      "xl-error-dark": "0 6px 16px var(--ui-pen-error-shadow-dark)",
      "xs-notification-dark": "0 1px 1px var(--ui-pen-notification-shadow-dark)",
      "sm-notification-dark": "0 1px 3px var(--ui-pen-notification-shadow-dark)",
      "md-notification-dark": "0 2px 6px var(--ui-pen-notification-shadow-dark)",
      "lg-notification-dark": "0 4px 10px var(--ui-pen-notification-shadow-dark)",
      "xl-notification-dark": "0 6px 16px var(--ui-pen-notification-shadow-dark)"
    },
    "blur": {
      "xs": "2px",
      "sm": "4px",
      "md": "8px",
      "lg": "16px",
      "xl": "32px"
    },
    "perspective": {
      "near": "300px",
      "normal": "600px",
      "distant": "1200px"
    },
    "tilt": {
      "xs": "4deg",
      "sm": "10deg",
      "md": "25deg",
      "lg": "45deg",
      "xl": "65deg"
    },
    "aspect": {
      "video": "16 / 9",
      "photo": "4 / 3",
      "square": "1 / 1",
      "portrait": "3 / 4",
      "tall": "9 / 16"
    }
  },
  "responsive": {
    "breakpoints": {
      "xs": "30rem",
      "sm": "40rem",
      "md": "48rem",
      "lg": "64rem",
      "xl": "80rem",
      "2xl": "96rem",
      "3xl": "120rem"
    },
    "containers": {
      "xs": "20rem",
      "sm": "24rem",
      "md": "28rem",
      "lg": "32rem",
      "xl": "36rem",
      "2xl": "42rem",
      "3xl": "48rem",
      "4xl": "56rem",
      "5xl": "64rem",
      "6xl": "72rem",
      "7xl": "80rem",
      "screen-sm": "var(--ui-breakpoint-sm)",
      "screen-md": "var(--ui-breakpoint-md)",
      "screen-lg": "var(--ui-breakpoint-lg)",
      "screen-xl": "var(--ui-breakpoint-xl)",
      "screen-2xl": "var(--ui-breakpoint-2xl)"
    }
  },
  "borders": {
    "widths": {
      "DEFAULT": "1px",
      "xs": "0.5px",
      "sm": "1px",
      "md": "2px",
      "lg": "3px",
      "xl": "4px"
    },
    "focusRing": {
      "width": "2px",
      "offset": "2px"
    },
    "ring": {
      "width": "2px"
    }
  },
  "motion": {
    "ease": {
      "in": "cubic-bezier(0.4, 0, 1, 1)",
      "out": "cubic-bezier(0, 0, 0.2, 1)",
      "in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
      "standard": "cubic-bezier(0.2, 0, 0, 1)",
      "enter": "var(--ui-ease-out)",
      "exit": "var(--ui-ease-in)",
      "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)"
    },
    "duration": {
      "fast": "100ms",
      "fast-exit": "75ms",
      "base": "150ms",
      "base-exit": "100ms",
      "slow": "250ms",
      "slow-exit": "200ms",
      "slower": "400ms",
      "slower-exit": "300ms"
    },
    "animate": {
      "spin": "spin 0.8s linear infinite",
      "ping": "ping 1s var(--ui-ease-out) infinite",
      "pulse": "pulse 2s var(--ui-ease-in-out) infinite",
      "skeleton": "skeleton 1.6s var(--ui-ease-in-out) infinite",
      "fade-in": "fade-in var(--ui-duration-slow) var(--ui-ease-enter) both",
      "slide-up": "slide-up var(--ui-duration-slow) var(--ui-ease-enter) both",
      "scale-in": "scale-in var(--ui-duration-slow) var(--ui-ease-enter) both"
    }
  },
  "assets": {}
} as const
const canonicalModes = {
  "light": {
    "fill-floor": {
      "default": "#edf0f4ff",
      "hover": "#e4e6eaff",
      "active": "#dadde0ff",
      "selected": "#d8dde3ff",
      "visited": "#edf0f4ff",
      "disabled": "#ebedefff",
      "focus": "#edf0f4ff",
      "pressed": "#d0d3d6ff",
      "on": "#d3d8deff",
      "error": "#edf0f4ff",
      "loading": "#edf0f4ff",
      "shadow": "#222f3f3d"
    },
    "fill-base": {
      "default": "#fcfdffff",
      "hover": "#f2f3f5ff",
      "active": "#e8e9ebff",
      "selected": "#e8eaecff",
      "visited": "#fcfdffff",
      "disabled": "#ebedefff",
      "focus": "#fcfdffff",
      "pressed": "#dfe0e1ff",
      "on": "#e3e5e7ff",
      "error": "#fcfdffff",
      "loading": "#fcfdffff",
      "shadow": "#222f3f3d"
    },
    "fill-primary": {
      "default": "#eef7ffff",
      "hover": "#e4edf5ff",
      "active": "#dbe3ebff",
      "selected": "#d6e4f0ff",
      "visited": "#eef7ffff",
      "disabled": "#ebedefff",
      "focus": "#eef7ffff",
      "pressed": "#d1d9e1ff",
      "on": "#d1dfebff",
      "error": "#eef7ffff",
      "loading": "#eef7ffff",
      "shadow": "#1f303e3d"
    },
    "fill-secondary": {
      "default": "#ebf8f0ff",
      "hover": "#e1eee6ff",
      "active": "#d7e4dcff",
      "selected": "#d2e7d9ff",
      "visited": "#ebf8f0ff",
      "disabled": "#ebeeecff",
      "focus": "#ebf8f0ff",
      "pressed": "#cedbd2ff",
      "on": "#cde2d5ff",
      "error": "#ebf8f0ff",
      "loading": "#ebf8f0ff",
      "shadow": "#1e33273d"
    },
    "fill-tertiary": {
      "default": "#e5f1f6ff",
      "hover": "#dbe7ecff",
      "active": "#d2dde2ff",
      "selected": "#ccdee6ff",
      "visited": "#e5f1f6ff",
      "disabled": "#eaedefff",
      "focus": "#e5f1f6ff",
      "pressed": "#c8d3d8ff",
      "on": "#c7d9e1ff",
      "error": "#e5f1f6ff",
      "loading": "#e5f1f6ff",
      "shadow": "#19323b3d"
    },
    "fill-accent": {
      "default": "#0668a4ff",
      "hover": "#025f98ff",
      "active": "#0a5788ff",
      "selected": "#085789ff",
      "visited": "#0668a4ff",
      "disabled": "#dadfe3ff",
      "focus": "#0668a4ff",
      "pressed": "#054e7dff",
      "on": "#005284ff",
      "error": "#0668a4ff",
      "loading": "#0668a4ff",
      "shadow": "#04598e47"
    },
    "fill-muted": {
      "default": "#e8ebefff",
      "hover": "#dfe1e5ff",
      "active": "#d5d8dbff",
      "selected": "#d3d8deff",
      "visited": "#e8ebefff",
      "disabled": "#ebedefff",
      "focus": "#e8ebefff",
      "pressed": "#cbced2ff",
      "on": "#ced3d9ff",
      "error": "#e8ebefff",
      "loading": "#e8ebefff",
      "shadow": "#222f3f3d"
    },
    "fill-input": {
      "default": "#ffffffff",
      "hover": "#f5f5f5ff",
      "active": "#ebebebff",
      "selected": "#e7ecf2ff",
      "visited": "#ffffffff",
      "disabled": "#ebedefff",
      "focus": "#ffffffff",
      "pressed": "#e1e1e1ff",
      "on": "#e2e7edff",
      "error": "#ffffffff",
      "loading": "#ffffffff",
      "shadow": "#222f3f3d"
    },
    "fill-link": {
      "default": "#fcfeffff",
      "hover": "#f2f3f5ff",
      "active": "#e8eaebff",
      "selected": "#e8eaebff",
      "visited": "#fcfeffff",
      "disabled": "#ebedefff",
      "focus": "#fcfeffff",
      "pressed": "#dee0e1ff",
      "on": "#e3e5e6ff",
      "error": "#fcfeffff",
      "loading": "#fcfeffff",
      "shadow": "#04598e47"
    },
    "fill-success": {
      "default": "#e2f9e6ff",
      "hover": "#d8efdcff",
      "active": "#cee5d2ff",
      "selected": "#c5e9cbff",
      "visited": "#e2f9e6ff",
      "disabled": "#ebedebff",
      "focus": "#e2f9e6ff",
      "pressed": "#c5dbc8ff",
      "on": "#c0e4c6ff",
      "error": "#e2f9e6ff",
      "loading": "#e2f9e6ff",
      "shadow": "#01672d47"
    },
    "fill-info": {
      "default": "#e3f4feff",
      "hover": "#d8eaf6ff",
      "active": "#cee0ecff",
      "selected": "#c5e2f5ff",
      "visited": "#e3f4feff",
      "disabled": "#eaedefff",
      "focus": "#e3f4feff",
      "pressed": "#c5d7e2ff",
      "on": "#c0ddf0ff",
      "error": "#e3f4feff",
      "loading": "#e3f4feff",
      "shadow": "#005d8247"
    },
    "fill-warning": {
      "default": "#fff1e0ff",
      "hover": "#fce6c9ff",
      "active": "#f2dcbfff",
      "selected": "#fcdaabff",
      "visited": "#fff1e0ff",
      "disabled": "#eeeceaff",
      "focus": "#fff1e0ff",
      "pressed": "#e8d2b6ff",
      "on": "#f7d5a6ff",
      "error": "#fff1e0ff",
      "loading": "#fff1e0ff",
      "shadow": "#724d0947"
    },
    "fill-error": {
      "default": "#feeceaff",
      "hover": "#fbe0ddff",
      "active": "#f1d6d3ff",
      "selected": "#fcd2cdff",
      "visited": "#feeceaff",
      "disabled": "#efecebff",
      "focus": "#feeceaff",
      "pressed": "#e7cdcaff",
      "on": "#f7cdc9ff",
      "error": "#feeceaff",
      "loading": "#feeceaff",
      "shadow": "#90302e47"
    },
    "fill-notification": {
      "default": "#d6f8f7ff",
      "hover": "#cceeedff",
      "active": "#c3e4e3ff",
      "selected": "#b2e9e8ff",
      "visited": "#d6f8f7ff",
      "disabled": "#eaeeedff",
      "focus": "#d6f8f7ff",
      "pressed": "#b9dadaff",
      "on": "#ade4e3ff",
      "error": "#d6f8f7ff",
      "loading": "#d6f8f7ff",
      "shadow": "#0a626247"
    },
    "pen-floor": {
      "default": "#292e35ff",
      "hover": "#1f242bff",
      "active": "#1f242bff",
      "selected": "#1f242bff",
      "visited": "#292e35ff",
      "disabled": "#7d8085ff",
      "focus": "#292e35ff",
      "pressed": "#1f242bff",
      "on": "#1f242bff",
      "error": "#292e35ff",
      "loading": "#292e35ff",
      "shadow": "#111b2859"
    },
    "pen-base": {
      "default": "#22272eff",
      "hover": "#181d24ff",
      "active": "#181d24ff",
      "selected": "#181d24ff",
      "visited": "#22272eff",
      "disabled": "#7d8085ff",
      "focus": "#22272eff",
      "pressed": "#181d24ff",
      "on": "#181d24ff",
      "error": "#22272eff",
      "loading": "#22272eff",
      "shadow": "#111b2859"
    },
    "pen-primary": {
      "default": "#0f304aff",
      "hover": "#04263fff",
      "active": "#04263fff",
      "selected": "#04263fff",
      "visited": "#0f304aff",
      "disabled": "#7c8185ff",
      "focus": "#0f304aff",
      "pressed": "#04263fff",
      "on": "#04263fff",
      "error": "#0f304aff",
      "loading": "#0f304aff",
      "shadow": "#0e1c2859"
    },
    "pen-secondary": {
      "default": "#113623ff",
      "hover": "#052c19ff",
      "active": "#052c19ff",
      "selected": "#052c19ff",
      "visited": "#113623ff",
      "disabled": "#7c827eff",
      "focus": "#113623ff",
      "pressed": "#052c19ff",
      "on": "#052c19ff",
      "error": "#113623ff",
      "loading": "#113623ff",
      "shadow": "#0e1f1559"
    },
    "pen-tertiary": {
      "default": "#122f3aff",
      "hover": "#072630ff",
      "active": "#072630ff",
      "selected": "#072630ff",
      "visited": "#122f3aff",
      "disabled": "#7b8184ff",
      "focus": "#122f3aff",
      "pressed": "#072630ff",
      "on": "#072630ff",
      "error": "#122f3aff",
      "loading": "#122f3aff",
      "shadow": "#091d2559"
    },
    "pen-accent": {
      "default": "#ffffffff",
      "hover": "#ffffffff",
      "active": "#ffffffff",
      "selected": "#ffffffff",
      "visited": "#ffffffff",
      "disabled": "#7c8185ff",
      "focus": "#ffffffff",
      "pressed": "#ffffffff",
      "on": "#ffffffff",
      "error": "#ffffffff",
      "loading": "#ffffffff",
      "shadow": "#0e1c2859"
    },
    "pen-muted": {
      "default": "#5e646cff",
      "hover": "#535961ff",
      "active": "#535961ff",
      "selected": "#535961ff",
      "visited": "#5e646cff",
      "disabled": "#7d8085ff",
      "focus": "#5e646cff",
      "pressed": "#51575fff",
      "on": "#535961ff",
      "error": "#5e646cff",
      "loading": "#5e646cff",
      "shadow": "#111b2859"
    },
    "pen-input": {
      "default": "#1d2229ff",
      "hover": "#14191fff",
      "active": "#14191fff",
      "selected": "#14191fff",
      "visited": "#1d2229ff",
      "disabled": "#7d8085ff",
      "focus": "#1d2229ff",
      "pressed": "#14191fff",
      "on": "#14191fff",
      "error": "#1d2229ff",
      "loading": "#1d2229ff",
      "shadow": "#111b2859"
    },
    "pen-link": {
      "default": "#0a5f96ff",
      "hover": "#005487ff",
      "active": "#005487ff",
      "selected": "#005487ff",
      "visited": "#065959ff",
      "disabled": "#7c8185ff",
      "focus": "#0a5f96ff",
      "pressed": "#005487ff",
      "on": "#005487ff",
      "error": "#0a5f96ff",
      "loading": "#0a5f96ff",
      "shadow": "#0e1c2859"
    },
    "pen-success": {
      "default": "#154f27ff",
      "hover": "#05441dff",
      "active": "#05441dff",
      "selected": "#05441dff",
      "visited": "#154f27ff",
      "disabled": "#7d827eff",
      "focus": "#154f27ff",
      "pressed": "#05441dff",
      "on": "#05441dff",
      "error": "#154f27ff",
      "loading": "#154f27ff",
      "shadow": "#101f1359"
    },
    "pen-info": {
      "default": "#064865ff",
      "hover": "#043d57ff",
      "active": "#043d57ff",
      "selected": "#043d57ff",
      "visited": "#064865ff",
      "disabled": "#7c8184ff",
      "focus": "#064865ff",
      "pressed": "#043d57ff",
      "on": "#043d57ff",
      "error": "#064865ff",
      "loading": "#064865ff",
      "shadow": "#0b1d2759"
    },
    "pen-warning": {
      "default": "#684506ff",
      "hover": "#5a3b05ff",
      "active": "#5a3b05ff",
      "selected": "#5a3b05ff",
      "visited": "#684506ff",
      "disabled": "#83807bff",
      "focus": "#684506ff",
      "pressed": "#5a3b05ff",
      "on": "#5a3b05ff",
      "error": "#684506ff",
      "loading": "#684506ff",
      "shadow": "#23190a59"
    },
    "pen-error": {
      "default": "#8d1a1eff",
      "hover": "#800613ff",
      "active": "#800613ff",
      "selected": "#800613ff",
      "visited": "#8d1a1eff",
      "disabled": "#857e7eff",
      "focus": "#8d1a1eff",
      "pressed": "#800613ff",
      "on": "#800613ff",
      "error": "#8d1a1eff",
      "loading": "#8d1a1eff",
      "shadow": "#27151359"
    },
    "pen-notification": {
      "default": "#084c4dff",
      "hover": "#044141ff",
      "active": "#044141ff",
      "selected": "#044141ff",
      "visited": "#084c4dff",
      "disabled": "#7b8282ff",
      "focus": "#084c4dff",
      "pressed": "#044141ff",
      "on": "#044141ff",
      "error": "#084c4dff",
      "loading": "#084c4dff",
      "shadow": "#071f1f59"
    },
    "edge-floor": {
      "default": "#747b83ff",
      "hover": "#6c727aff",
      "active": "#626a74ff",
      "selected": "#626a74ff",
      "visited": "#747b83ff",
      "disabled": "#747b83ff",
      "focus": "#0c60a3ff",
      "pressed": "#5b6169ff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#747b83ff"
    },
    "edge-base": {
      "default": "#747b83ff",
      "hover": "#6c727aff",
      "active": "#626a74ff",
      "selected": "#626a74ff",
      "visited": "#747b83ff",
      "disabled": "#747b83ff",
      "focus": "#0c60a3ff",
      "pressed": "#5b6169ff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#747b83ff"
    },
    "edge-primary": {
      "default": "#567896ff",
      "hover": "#4e708dff",
      "active": "#3a688dff",
      "selected": "#3a688dff",
      "visited": "#567896ff",
      "disabled": "#567896ff",
      "focus": "#0c60a3ff",
      "pressed": "#3d5e7aff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#567896ff"
    },
    "edge-secondary": {
      "default": "#567f67ff",
      "hover": "#4d775fff",
      "active": "#387152ff",
      "selected": "#387152ff",
      "visited": "#567f67ff",
      "disabled": "#567f67ff",
      "focus": "#0c60a3ff",
      "pressed": "#3c654eff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#567f67ff"
    },
    "edge-tertiary": {
      "default": "#587783ff",
      "hover": "#506e7aff",
      "active": "#3e6777ff",
      "selected": "#3e6777ff",
      "visited": "#587783ff",
      "disabled": "#587783ff",
      "focus": "#0c60a3ff",
      "pressed": "#3f5d69ff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#587783ff"
    },
    "edge-accent": {
      "default": "#83c5fcff",
      "hover": "#7bb8ebff",
      "active": "#77aedcff",
      "selected": "#77aedcff",
      "visited": "#83c5fcff",
      "disabled": "#c1c4c8ff",
      "focus": "#0c60a3ff",
      "pressed": "#7fa0bcff",
      "on": "#62a8e3ff",
      "error": "#ecb0aaff",
      "loading": "#83c5fcff"
    },
    "edge-muted": {
      "default": "#81878dff",
      "hover": "#797e84ff",
      "active": "#6e757eff",
      "selected": "#6e757eff",
      "visited": "#81878dff",
      "disabled": "#81878dff",
      "focus": "#0c60a3ff",
      "pressed": "#676c73ff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#81878dff"
    },
    "edge-input": {
      "default": "#6d7580ff",
      "hover": "#646d78ff",
      "active": "#596472ff",
      "selected": "#596472ff",
      "visited": "#6d7580ff",
      "disabled": "#6d7580ff",
      "focus": "#0c60a3ff",
      "pressed": "#535c66ff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#6d7580ff"
    },
    "edge-link": {
      "default": "#0a5f96ff",
      "hover": "#05578aff",
      "active": "#094e7cff",
      "selected": "#094e7cff",
      "visited": "#0a5f96ff",
      "disabled": "#0a5f96ff",
      "focus": "#0c60a3ff",
      "pressed": "#044670ff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#0a5f96ff"
    },
    "edge-success": {
      "default": "#3b834eff",
      "hover": "#317a45ff",
      "active": "#0f7436ff",
      "selected": "#0f7436ff",
      "visited": "#3b834eff",
      "disabled": "#3b834eff",
      "focus": "#0c60a3ff",
      "pressed": "#1d6835ff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#3b834eff"
    },
    "edge-info": {
      "default": "#177ba8ff",
      "hover": "#01729fff",
      "active": "#0d6891ff",
      "selected": "#0d6891ff",
      "visited": "#177ba8ff",
      "disabled": "#177ba8ff",
      "focus": "#0c60a3ff",
      "pressed": "#095f85ff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#177ba8ff"
    },
    "edge-warning": {
      "default": "#a36e09ff",
      "hover": "#986607ff",
      "active": "#8d5e02ff",
      "selected": "#8d5e02ff",
      "visited": "#a36e09ff",
      "disabled": "#a36e09ff",
      "focus": "#0c60a3ff",
      "pressed": "#825601ff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#a36e09ff"
    },
    "edge-error": {
      "default": "#ba3535ff",
      "hover": "#b02a2dff",
      "active": "#ac021aff",
      "selected": "#ac021aff",
      "visited": "#ba3535ff",
      "disabled": "#ba3535ff",
      "focus": "#0c60a3ff",
      "pressed": "#9b0f1bff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#ba3535ff"
    },
    "edge-notification": {
      "default": "#128282ff",
      "hover": "#0e7878ff",
      "active": "#076f6fff",
      "selected": "#076f6fff",
      "visited": "#128282ff",
      "disabled": "#128282ff",
      "focus": "#0c60a3ff",
      "pressed": "#046565ff",
      "on": "#04598eff",
      "error": "#ba2b2eff",
      "loading": "#128282ff"
    }
  },
  "dark": {
    "fill-floor": {
      "default": "#090b0eff",
      "hover": "#101214ff",
      "active": "#16181bff",
      "selected": "#15191dff",
      "visited": "#090b0eff",
      "disabled": "#1f2122ff",
      "focus": "#090b0eff",
      "pressed": "#1d1f22ff",
      "on": "#191c20ff",
      "error": "#090b0eff",
      "loading": "#090b0eff",
      "shadow": "#000001b3"
    },
    "fill-base": {
      "default": "#131519ff",
      "hover": "#191c20ff",
      "active": "#202327ff",
      "selected": "#1f2329ff",
      "visited": "#131519ff",
      "disabled": "#1f2122ff",
      "focus": "#131519ff",
      "pressed": "#272a2eff",
      "on": "#22272dff",
      "error": "#131519ff",
      "loading": "#131519ff",
      "shadow": "#000001b3"
    },
    "fill-primary": {
      "default": "#151f28ff",
      "hover": "#1c262fff",
      "active": "#232e37ff",
      "selected": "#1d2e3dff",
      "visited": "#151f28ff",
      "disabled": "#1f2122ff",
      "focus": "#151f28ff",
      "pressed": "#2b353fff",
      "on": "#213241ff",
      "error": "#151f28ff",
      "loading": "#151f28ff",
      "shadow": "#000001b3"
    },
    "fill-secondary": {
      "default": "#18271eff",
      "hover": "#202e25ff",
      "active": "#27362dff",
      "selected": "#1f382aff",
      "visited": "#18271eff",
      "disabled": "#1f2120ff",
      "focus": "#18271eff",
      "pressed": "#2e3d34ff",
      "on": "#233c2dff",
      "error": "#18271eff",
      "loading": "#18271eff",
      "shadow": "#000000b3"
    },
    "fill-tertiary": {
      "default": "#1f2c32ff",
      "hover": "#273439ff",
      "active": "#2e3c41ff",
      "selected": "#273d46ff",
      "visited": "#1f2c32ff",
      "disabled": "#1e2122ff",
      "focus": "#1f2c32ff",
      "pressed": "#364349ff",
      "on": "#2a414aff",
      "error": "#1f2c32ff",
      "loading": "#1f2c32ff",
      "shadow": "#000001b3"
    },
    "fill-accent": {
      "default": "#72b8f2ff",
      "hover": "#7cc2fdff",
      "active": "#90cbfeff",
      "selected": "#8fcbfeff",
      "visited": "#72b8f2ff",
      "disabled": "#35383cff",
      "focus": "#72b8f2ff",
      "pressed": "#a4d4fdff",
      "on": "#9acffeff",
      "error": "#72b8f2ff",
      "loading": "#72b8f2ff",
      "shadow": "#348dcf59"
    },
    "fill-muted": {
      "default": "#24272aff",
      "hover": "#2b2e32ff",
      "active": "#33363aff",
      "selected": "#31363cff",
      "visited": "#24272aff",
      "disabled": "#1f2122ff",
      "focus": "#24272aff",
      "pressed": "#3a3d41ff",
      "on": "#353a40ff",
      "error": "#24272aff",
      "loading": "#24272aff",
      "shadow": "#000001b3"
    },
    "fill-input": {
      "default": "#191c20ff",
      "hover": "#202328ff",
      "active": "#272a2fff",
      "selected": "#252b32ff",
      "visited": "#191c20ff",
      "disabled": "#1f2122ff",
      "focus": "#191c20ff",
      "pressed": "#2e3237ff",
      "on": "#282e36ff",
      "error": "#191c20ff",
      "loading": "#191c20ff",
      "shadow": "#000001b3"
    },
    "fill-link": {
      "default": "#121518ff",
      "hover": "#191c1fff",
      "active": "#202326ff",
      "selected": "#1e2429ff",
      "visited": "#121518ff",
      "disabled": "#1f2122ff",
      "focus": "#121518ff",
      "pressed": "#272b2eff",
      "on": "#21272cff",
      "error": "#121518ff",
      "loading": "#121518ff",
      "shadow": "#348dcf59"
    },
    "fill-success": {
      "default": "#152d1aff",
      "hover": "#1c3422ff",
      "active": "#243c29ff",
      "selected": "#143f21ff",
      "visited": "#152d1aff",
      "disabled": "#1f211fff",
      "focus": "#152d1aff",
      "pressed": "#2c4431ff",
      "on": "#194324ff",
      "error": "#152d1aff",
      "loading": "#152d1aff",
      "shadow": "#429c5a59"
    },
    "fill-info": {
      "default": "#112937ff",
      "hover": "#18313fff",
      "active": "#203947ff",
      "selected": "#093a51ff",
      "visited": "#112937ff",
      "disabled": "#1f2122ff",
      "focus": "#112937ff",
      "pressed": "#28414fff",
      "on": "#0f3e56ff",
      "error": "#112937ff",
      "loading": "#112937ff",
      "shadow": "#0891c959"
    },
    "fill-warning": {
      "default": "#342611ff",
      "hover": "#3c2d18ff",
      "active": "#443520ff",
      "selected": "#4b320aff",
      "visited": "#342611ff",
      "disabled": "#22201eff",
      "focus": "#342611ff",
      "pressed": "#4c3d27ff",
      "on": "#4f360fff",
      "error": "#342611ff",
      "loading": "#342611ff",
      "shadow": "#b3790359"
    },
    "fill-error": {
      "default": "#3b1c1aff",
      "hover": "#442321ff",
      "active": "#4c2b28ff",
      "selected": "#572220ff",
      "visited": "#3b1c1aff",
      "disabled": "#22201fff",
      "focus": "#3b1c1aff",
      "pressed": "#553330ff",
      "on": "#5c2623ff",
      "error": "#3b1c1aff",
      "loading": "#3b1c1aff",
      "shadow": "#c8635d59"
    },
    "fill-notification": {
      "default": "#0a2e2eff",
      "hover": "#123535ff",
      "active": "#1b3d3dff",
      "selected": "#053f3fff",
      "visited": "#0a2e2eff",
      "disabled": "#1e2121ff",
      "focus": "#0a2e2eff",
      "pressed": "#234545ff",
      "on": "#044444ff",
      "error": "#0a2e2eff",
      "loading": "#0a2e2eff",
      "shadow": "#1b999959"
    },
    "pen-floor": {
      "default": "#dadee5ff",
      "hover": "#e3e8efff",
      "active": "#e3e8efff",
      "selected": "#e3e8efff",
      "visited": "#dadee5ff",
      "disabled": "#6e7276ff",
      "focus": "#dadee5ff",
      "pressed": "#e3e8efff",
      "on": "#e3e8efff",
      "error": "#dadee5ff",
      "loading": "#dadee5ff",
      "shadow": "#000001cc"
    },
    "pen-base": {
      "default": "#e8ebf1ff",
      "hover": "#f2f5fbff",
      "active": "#f2f5fbff",
      "selected": "#f2f5fbff",
      "visited": "#e8ebf1ff",
      "disabled": "#6e7276ff",
      "focus": "#e8ebf1ff",
      "pressed": "#f2f5fbff",
      "on": "#f2f5fbff",
      "error": "#e8ebf1ff",
      "loading": "#e8ebf1ff",
      "shadow": "#000001cc"
    },
    "pen-primary": {
      "default": "#dbeaf8ff",
      "hover": "#e7f4ffff",
      "active": "#e7f4ffff",
      "selected": "#e7f4ffff",
      "visited": "#dbeaf8ff",
      "disabled": "#6e7276ff",
      "focus": "#dbeaf8ff",
      "pressed": "#e7f4ffff",
      "on": "#e7f4ffff",
      "error": "#dbeaf8ff",
      "loading": "#dbeaf8ff",
      "shadow": "#000001cc"
    },
    "pen-secondary": {
      "default": "#d8eee0ff",
      "hover": "#e2f8eaff",
      "active": "#e2f8eaff",
      "selected": "#e2f8eaff",
      "visited": "#d8eee0ff",
      "disabled": "#6e7370ff",
      "focus": "#d8eee0ff",
      "pressed": "#e2f8eaff",
      "on": "#e2f8eaff",
      "error": "#d8eee0ff",
      "loading": "#d8eee0ff",
      "shadow": "#000100cc"
    },
    "pen-tertiary": {
      "default": "#deeef5ff",
      "hover": "#e8f8ffff",
      "active": "#e8f8ffff",
      "selected": "#e8f8ffff",
      "visited": "#deeef5ff",
      "disabled": "#6d7375ff",
      "focus": "#deeef5ff",
      "pressed": "#e8f8ffff",
      "on": "#e8f8ffff",
      "error": "#deeef5ff",
      "loading": "#deeef5ff",
      "shadow": "#000101cc"
    },
    "pen-accent": {
      "default": "#06131eff",
      "hover": "#06131eff",
      "active": "#06131eff",
      "selected": "#06131eff",
      "visited": "#06131eff",
      "disabled": "#667785ff",
      "focus": "#06131eff",
      "pressed": "#06131eff",
      "on": "#06131eff",
      "error": "#06131eff",
      "loading": "#06131eff",
      "shadow": "#000001cc"
    },
    "pen-muted": {
      "default": "#a6abb2ff",
      "hover": "#afb5bcff",
      "active": "#afb5bcff",
      "selected": "#afb5bcff",
      "visited": "#a6abb2ff",
      "disabled": "#6e7276ff",
      "focus": "#a6abb2ff",
      "pressed": "#afb5bcff",
      "on": "#afb5bcff",
      "error": "#a6abb2ff",
      "loading": "#a6abb2ff",
      "shadow": "#000001cc"
    },
    "pen-input": {
      "default": "#ebeff4ff",
      "hover": "#f5f9feff",
      "active": "#f5f9feff",
      "selected": "#f5f9feff",
      "visited": "#ebeff4ff",
      "disabled": "#6e7276ff",
      "focus": "#ebeff4ff",
      "pressed": "#f5f9feff",
      "on": "#f5f9feff",
      "error": "#ebeff4ff",
      "loading": "#ebeff4ff",
      "shadow": "#000001cc"
    },
    "pen-link": {
      "default": "#7fbef3ff",
      "hover": "#89c8feff",
      "active": "#89c8feff",
      "selected": "#89c8feff",
      "visited": "#72d0d0ff",
      "disabled": "#6e7276ff",
      "focus": "#7fbef3ff",
      "pressed": "#89c8feff",
      "on": "#89c8feff",
      "error": "#7fbef3ff",
      "loading": "#7fbef3ff",
      "shadow": "#000001cc"
    },
    "pen-success": {
      "default": "#b2e7bcff",
      "hover": "#bcf1c6ff",
      "active": "#bcf1c6ff",
      "selected": "#bcf1c6ff",
      "visited": "#b2e7bcff",
      "disabled": "#6e736fff",
      "focus": "#b2e7bcff",
      "pressed": "#bcf1c6ff",
      "on": "#bcf1c6ff",
      "error": "#b2e7bcff",
      "loading": "#b2e7bcff",
      "shadow": "#000100cc"
    },
    "pen-info": {
      "default": "#b2dffaff",
      "hover": "#c3e7feff",
      "active": "#c3e7feff",
      "selected": "#c3e7feff",
      "visited": "#b2dffaff",
      "disabled": "#6d7276ff",
      "focus": "#b2dffaff",
      "pressed": "#c3e7feff",
      "on": "#c3e7feff",
      "error": "#b2dffaff",
      "loading": "#b2dffaff",
      "shadow": "#000001cc"
    },
    "pen-warning": {
      "default": "#fed7a3ff",
      "hover": "#fee3bfff",
      "active": "#fee3bfff",
      "selected": "#fee3bfff",
      "visited": "#fed7a3ff",
      "disabled": "#74716cff",
      "focus": "#fed7a3ff",
      "pressed": "#fee3bfff",
      "on": "#fee3bfff",
      "error": "#fed7a3ff",
      "loading": "#fed7a3ff",
      "shadow": "#010000cc"
    },
    "pen-error": {
      "default": "#ffc8c3ff",
      "hover": "#fed7d3ff",
      "active": "#fed7d3ff",
      "selected": "#fed7d3ff",
      "visited": "#ffc8c3ff",
      "disabled": "#76706fff",
      "focus": "#ffc8c3ff",
      "pressed": "#fed7d3ff",
      "on": "#fed7d3ff",
      "error": "#ffc8c3ff",
      "loading": "#ffc8c3ff",
      "shadow": "#010000cc"
    },
    "pen-notification": {
      "default": "#b0ebeaff",
      "hover": "#b9f5f4ff",
      "active": "#b9f5f4ff",
      "selected": "#b9f5f4ff",
      "visited": "#b0ebeaff",
      "disabled": "#6c7373ff",
      "focus": "#b0ebeaff",
      "pressed": "#b9f5f4ff",
      "on": "#b9f5f4ff",
      "error": "#b0ebeaff",
      "loading": "#b0ebeaff",
      "shadow": "#000101cc"
    },
    "edge-floor": {
      "default": "#81878dff",
      "hover": "#8a9097ff",
      "active": "#9299a2ff",
      "selected": "#9299a2ff",
      "visited": "#81878dff",
      "disabled": "#404346ff",
      "focus": "#71bfffff",
      "pressed": "#9da2a9ff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#81878dff"
    },
    "edge-base": {
      "default": "#81878dff",
      "hover": "#8a9097ff",
      "active": "#9299a2ff",
      "selected": "#9299a2ff",
      "visited": "#81878dff",
      "disabled": "#404346ff",
      "focus": "#71bfffff",
      "pressed": "#9da2a9ff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#81878dff"
    },
    "edge-primary": {
      "default": "#7390a9ff",
      "hover": "#7c99b2ff",
      "active": "#7da3c5ff",
      "selected": "#7da3c5ff",
      "visited": "#7390a9ff",
      "disabled": "#404345ff",
      "focus": "#71bfffff",
      "pressed": "#8eacc6ff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#7390a9ff"
    },
    "edge-secondary": {
      "default": "#769d85ff",
      "hover": "#7fa68eff",
      "active": "#7eb394ff",
      "selected": "#7eb394ff",
      "visited": "#769d85ff",
      "disabled": "#404341ff",
      "focus": "#71bfffff",
      "pressed": "#91b9a1ff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#769d85ff"
    },
    "edge-tertiary": {
      "default": "#829da9ff",
      "hover": "#8ba7b2ff",
      "active": "#8db1c1ff",
      "selected": "#8db1c1ff",
      "visited": "#829da9ff",
      "disabled": "#3f4345ff",
      "focus": "#71bfffff",
      "pressed": "#9db9c5ff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#829da9ff"
    },
    "edge-accent": {
      "default": "#495d6fff",
      "hover": "#44647fff",
      "active": "#546a7dff",
      "selected": "#546a7dff",
      "visited": "#495d6fff",
      "disabled": "#404345ff",
      "focus": "#71bfffff",
      "pressed": "#63717dff",
      "on": "#316fa0ff",
      "error": "#a33131ff",
      "loading": "#495d6fff"
    },
    "edge-muted": {
      "default": "#70757cff",
      "hover": "#797e84ff",
      "active": "#808790ff",
      "selected": "#808790ff",
      "visited": "#70757cff",
      "disabled": "#404346ff",
      "focus": "#71bfffff",
      "pressed": "#8a9097ff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#70757cff"
    },
    "edge-input": {
      "default": "#8a939fff",
      "hover": "#939ca8ff",
      "active": "#9aa6b5ff",
      "selected": "#9aa6b5ff",
      "visited": "#8a939fff",
      "disabled": "#404346ff",
      "focus": "#71bfffff",
      "pressed": "#a6afbbff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#8a939fff"
    },
    "edge-link": {
      "default": "#7fbef3ff",
      "hover": "#89c8feff",
      "active": "#9ed1fdff",
      "selected": "#9ed1fdff",
      "visited": "#7fbef3ff",
      "disabled": "#404345ff",
      "focus": "#71bfffff",
      "pressed": "#b0dafeff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#7fbef3ff"
    },
    "edge-success": {
      "default": "#69b27aff",
      "hover": "#73bb83ff",
      "active": "#66ca7fff",
      "selected": "#66ca7fff",
      "visited": "#69b27aff",
      "disabled": "#404341ff",
      "focus": "#71bfffff",
      "pressed": "#85cf95ff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#69b27aff"
    },
    "edge-info": {
      "default": "#69aed5ff",
      "hover": "#73b7dfff",
      "active": "#64c3f7ff",
      "selected": "#64c3f7ff",
      "visited": "#69aed5ff",
      "disabled": "#3f4345ff",
      "focus": "#71bfffff",
      "pressed": "#86cbf3ff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#69aed5ff"
    },
    "edge-warning": {
      "default": "#daa24fff",
      "hover": "#e4ac59ff",
      "active": "#fbb033ff",
      "selected": "#fbb033ff",
      "visited": "#daa24fff",
      "disabled": "#44423fff",
      "focus": "#71bfffff",
      "pressed": "#f8bf6cff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#daa24fff"
    },
    "edge-error": {
      "default": "#ed756eff",
      "hover": "#f87e77ff",
      "active": "#fc8c85ff",
      "selected": "#fc8c85ff",
      "visited": "#ed756eff",
      "disabled": "#454141ff",
      "focus": "#71bfffff",
      "pressed": "#fc9c95ff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#ed756eff"
    },
    "edge-notification": {
      "default": "#57b6b6ff",
      "hover": "#61c0bfff",
      "active": "#42ceceff",
      "selected": "#42ceceff",
      "visited": "#57b6b6ff",
      "disabled": "#3f4343ff",
      "focus": "#71bfffff",
      "pressed": "#75d3d3ff",
      "on": "#86c5faff",
      "error": "#f47b74ff",
      "loading": "#57b6b6ff"
    }
  }
} as const

function mergeRecord(base: Record<string, unknown>, override: Record<string, unknown>): Record<string, unknown> {
  const result = structuredClone(base)
  for (const [key, value] of Object.entries(override)) {
    if (value && typeof value === 'object' && !Array.isArray(value)
      && result[key] && typeof result[key] === 'object' && !Array.isArray(result[key])) {
      result[key] = mergeRecord(result[key] as Record<string, unknown>, value as Record<string, unknown>)
    }
    else result[key] = structuredClone(value)
  }
  return result
}

export function createCanonicalThemeDefinition(options: { id?: string; name?: string; description?: string; ownerType?: ThemeOwnerType; ownerId?: string } = {}): ThemeDefinition {
  const ownerType = options.ownerType ?? 'system'
  if (ownerType !== 'system' && !options.ownerId) throw new TypeError('ownerId is required for non-system canonical themes.')
  return structuredClone({
    id: options.id ?? 'theme-manager-default',
    name: options.name ?? 'Theme Manager Default',
    description: options.description ?? 'Canonical complete Theme Manager presentation vocabulary.',
    // A system Theme's version is the release it ships in; others start at 1.0.0.
    version: ownerType === 'system' ? THEME_MANAGER_VERSION : '1.0.0',
    schemaVersion: THEME_VOCABULARY_VERSION,
    ownership: { ownerType, ...(options.ownerId ? { ownerId: options.ownerId } : {}) },
    visibility: ownerType === 'system' ? 'system' : 'private',
    lifecycle: ownerType === 'system' ? 'published' : 'draft',
    presentation: canonicalPresentation,
    modes: canonicalModes,
  }) as ThemeDefinition
}

export function completeThemeVocabulary(theme: ThemeDefinition): ThemeDefinition {
  const canonical = createCanonicalThemeDefinition()
  return {
    ...structuredClone(theme),
    presentation: mergeRecord(canonical.presentation as unknown as Record<string, unknown>, theme.presentation as unknown as Record<string, unknown>) as unknown as ThemeDefinition['presentation'],
    modes: mergeRecord(canonical.modes as unknown as Record<string, unknown>, theme.modes as unknown as Record<string, unknown>) as ThemeDefinition['modes'],
  }
}

export function themeVocabularyCardinality(theme: ThemeDefinition) {
  const mode = theme.modes.light as Record<string, Record<string, unknown>> | undefined
  const colour = mode ? Object.values(mode).reduce((total, states) => total + Object.keys(states).length, 0) : 0
  const countNested = (value: Record<string, unknown>) =>
    Object.values(value).reduce<number>((total, family) => total + (family && typeof family === 'object' && !Array.isArray(family) ? Object.keys(family).length : 0), 0)
  const typography = countNested(theme.presentation.typography)
  const effects = countNested(theme.presentation.effects)
  const responsive = countNested(theme.presentation.responsive)
  const spacing = Object.keys(theme.presentation.spacing).length
  const radii = Object.keys(theme.presentation.radii).length
  const borders = countNested(theme.presentation.borders ?? {})
  const motion = countNested(theme.presentation.motion ?? {})
  return {
    colour, typography, spacing, radii, effects, responsive, borders, motion,
    total: colour + typography + spacing + radii + effects + responsive + borders + motion,
  }
}

export function assertCompleteThemeVocabulary(theme: ThemeDefinition): ThemeDefinition {
  const actual = themeVocabularyCardinality(theme)
  for (const key of ['colour', 'typography', 'spacing', 'radii', 'effects', 'responsive', 'borders', 'motion', 'total'] as const) {
    if (actual[key] < CANONICAL_THEME_CARDINALITY[key]) {
      throw new TypeError(`Theme vocabulary is incomplete: ${key} has ${actual[key]} entries; expected at least ${CANONICAL_THEME_CARDINALITY[key]}.`)
    }
  }
  return theme
}
