import type { ThemeDefinition, ThemeOwnerType } from '../contracts'

export const CANONICAL_THEME_CARDINALITY = {
  "colour": 280,
  "typography": 17,
  "spacing": 31,
  "radii": 6,
  "effects": 228,
  "responsive": 10,
  "total": 572
} as const

const canonicalPresentation = {
  "colour": {
    "roles": {
      "fill-base": true,
      "fill-primary": true,
      "fill-secondary": true,
      "fill-tertiary": true,
      "fill-accent": true,
      "fill-muted": true,
      "fill-floor": true,
      "fill-input": true,
      "fill-link": true,
      "fill-success": true,
      "fill-info": true,
      "fill-warning": true,
      "fill-error": true,
      "fill-notification": true,
      "pen-base": true,
      "pen-primary": true,
      "pen-secondary": true,
      "pen-tertiary": true,
      "pen-accent": true,
      "pen-muted": true,
      "pen-floor": true,
      "pen-input": true,
      "pen-link": true,
      "pen-success": true,
      "pen-info": true,
      "pen-warning": true,
      "pen-error": true,
      "pen-notification": true,
      "edge-base": true,
      "edge-primary": true,
      "edge-secondary": true,
      "edge-tertiary": true,
      "edge-accent": true,
      "edge-muted": true,
      "edge-floor": true,
      "edge-input": true,
      "edge-link": true,
      "edge-success": true,
      "edge-info": true,
      "edge-warning": true,
      "edge-error": true,
      "edge-notification": true
    }
  },
  "typography": {
    "families": {
      "sans": "\"Inter\", \"Helvetica Neue\", Arial, sans-serif",
      "serif": "\"Merriweather\", serif",
      "mono": "\"Fira Code\", \"Courier New\", monospace"
    },
    "sizes": {
      "sm": "0.875rem",
      "base": "1rem",
      "lg": "1.125rem",
      "xl": "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.0rem"
    },
    "weights": {
      "light": "300",
      "normal": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700",
      "extrabold": "800",
      "heavy": "900"
    }
  },
  "spacing": {
    "1": "var(--spacing-p-xs)",
    "2": "var(--spacing-p-sm)",
    "3": "12px",
    "4": "var(--spacing-p-md)",
    "5": "20px",
    "6": "var(--spacing-p-lg)",
    "7": "var(--spacing-p-xl)",
    "8": "48px",
    "9": "64px",
    "p-xs": "4px",
    "p-sm": "8px",
    "p-md": "16px",
    "p-lg": "24px",
    "p-xl": "32px",
    "xs": "20rem",
    "sm": "24rem",
    "md": "28rem",
    "lg": "32rem",
    "xl": "36rem",
    "2xl": "42rem",
    "3xl": "48rem",
    "4xl": "56rem",
    "5xl": "64rem",
    "6xl": "72rem",
    "7xl": "80rem",
    "full": "100%",
    "screen-sm": "640px",
    "screen-md": "768px",
    "screen-lg": "1024px",
    "screen-xl": "1280px",
    "screen-2xl": "1536px"
  },
  "radii": {
    "sm": "2px",
    "md": "4px",
    "lg": "8px",
    "xl": "16px",
    "DEFAULT": "var(--radius-md)",
    "full": "var(calc(infinity * 1px))"
  },
  "effects": {
    "shadow": {
      "sm-base": "0 1px 2px 0 var(--color-fill-base-shadow)",
      "md-base": "0 4px 6px -1px var(--color-fill-base-shadow), 0 2px 4px -2px var(--color-fill-base-shadow)",
      "lg-base": "0 10px 15px -3px var(--color-fill-base-shadow), 0 4px 6px -4px var(--color-fill-base-shadow)",
      "xl-base": "0 20px 25px -5px var(--color-fill-base-shadow), 0 8px 10px -6px var(--color-fill-base-shadow)",
      "sm-primary": "0 1px 2px 0 var(--color-fill-primary-shadow)",
      "md-primary": "0 4px 6px -1px var(--color-fill-primary-shadow), 0 2px 4px -2px var(--color-fill-primary-shadow)",
      "lg-primary": "0 10px 15px -3px var(--color-fill-primary-shadow), 0 4px 6px -4px var(--color-fill-primary-shadow)",
      "xl-primary": "0 20px 25px -5px var(--color-fill-primary-shadow), 0 8px 10px -6px var(--color-fill-primary-shadow)",
      "sm-secondary": "0 1px 2px 0 var(--color-fill-secondary-shadow)",
      "md-secondary": "0 4px 6px -1px var(--color-fill-secondary-shadow), 0 2px 4px -2px var(--color-fill-secondary-shadow)",
      "lg-secondary": "0 10px 15px -3px var(--color-fill-secondary-shadow), 0 4px 6px -4px var(--color-fill-secondary-shadow)",
      "xl-secondary": "0 20px 25px -5px var(--color-fill-secondary-shadow), 0 8px 10px -6px var(--color-fill-secondary-shadow)",
      "sm-tertiary": "0 1px 2px 0 var(--color-fill-tertiary-shadow)",
      "md-tertiary": "0 4px 6px -1px var(--color-fill-tertiary-shadow), 0 2px 4px -2px var(--color-fill-tertiary-shadow)",
      "lg-tertiary": "0 10px 15px -3px var(--color-fill-tertiary-shadow), 0 4px 6px -4px var(--color-fill-tertiary-shadow)",
      "xl-tertiary": "0 20px 25px -5px var(--color-fill-tertiary-shadow), 0 8px 10px -6px var(--color-fill-tertiary-shadow)",
      "sm-accent": "0 1px 2px 0 var(--color-fill-accent-shadow)",
      "md-accent": "0 4px 6px -1px var(--color-fill-accent-shadow), 0 2px 4px -2px var(--color-fill-accent-shadow)",
      "lg-accent": "0 10px 15px -3px var(--color-fill-accent-shadow), 0 4px 6px -4px var(--color-fill-accent-shadow)",
      "xl-accent": "0 20px 25px -5px var(--color-fill-accent-shadow), 0 8px 10px -6px var(--color-fill-accent-shadow)",
      "sm-muted": "0 1px 2px 0 var(--color-fill-muted-shadow)",
      "md-muted": "0 4px 6px -1px var(--color-fill-muted-shadow), 0 2px 4px -2px var(--color-fill-muted-shadow)",
      "lg-muted": "0 10px 15px -3px var(--color-fill-muted-shadow), 0 4px 6px -4px var(--color-fill-muted-shadow)",
      "xl-muted": "0 20px 25px -5px var(--color-fill-muted-shadow), 0 8px 10px -6px var(--color-fill-muted-shadow)",
      "sm-floor": "0 1px 2px 0 var(--color-fill-floor-shadow)",
      "md-floor": "0 4px 6px -1px var(--color-fill-floor-shadow), 0 2px 4px -2px var(--color-fill-floor-shadow)",
      "lg-floor": "0 10px 15px -3px var(--color-fill-floor-shadow), 0 4px 6px -4px var(--color-fill-floor-shadow)",
      "xl-floor": "0 20px 25px -5px var(--color-fill-floor-shadow), 0 8px 10px -6px var(--color-fill-floor-shadow)",
      "sm-input": "0 1px 2px 0 var(--color-fill-input-shadow)",
      "md-input": "0 4px 6px -1px var(--color-fill-input-shadow), 0 2px 4px -2px var(--color-fill-input-shadow)",
      "lg-input": "0 10px 15px -3px var(--color-fill-input-shadow), 0 4px 6px -4px var(--color-fill-input-shadow)",
      "xl-input": "0 20px 25px -5px var(--color-fill-input-shadow), 0 8px 10px -6px var(--color-fill-input-shadow)",
      "sm-link": "0 1px 2px 0 var(--color-fill-link-shadow)",
      "md-link": "0 4px 6px -1px var(--color-fill-link-shadow), 0 2px 4px -2px var(--color-fill-link-shadow)",
      "lg-link": "0 10px 15px -3px var(--color-fill-link-shadow), 0 4px 6px -4px var(--color-fill-link-shadow)",
      "xl-link": "0 20px 25px -5px var(--color-fill-link-shadow), 0 8px 10px -6px var(--color-fill-link-shadow)",
      "sm-success": "0 1px 2px 0 var(--color-fill-success-shadow)",
      "md-success": "0 4px 6px -1px var(--color-fill-success-shadow), 0 2px 4px -2px var(--color-fill-success-shadow)",
      "lg-success": "0 10px 15px -3px var(--color-fill-success-shadow), 0 4px 6px -4px var(--color-fill-success-shadow)",
      "xl-success": "0 20px 25px -5px var(--color-fill-success-shadow), 0 8px 10px -6px var(--color-fill-success-shadow)",
      "sm-info": "0 1px 2px 0 var(--color-fill-info-shadow)",
      "md-info": "0 4px 6px -1px var(--color-fill-info-shadow), 0 2px 4px -2px var(--color-fill-info-shadow)",
      "lg-info": "0 10px 15px -3px var(--color-fill-info-shadow), 0 4px 6px -4px var(--color-fill-info-shadow)",
      "xl-info": "0 20px 25px -5px var(--color-fill-info-shadow), 0 8px 10px -6px var(--color-fill-info-shadow)",
      "sm-warning": "0 1px 2px 0 var(--color-fill-warning-shadow)",
      "md-warning": "0 4px 6px -1px var(--color-fill-warning-shadow), 0 2px 4px -2px var(--color-fill-warning-shadow)",
      "lg-warning": "0 10px 15px -3px var(--color-fill-warning-shadow), 0 4px 6px -4px var(--color-fill-warning-shadow)",
      "xl-warning": "0 20px 25px -5px var(--color-fill-warning-shadow), 0 8px 10px -6px var(--color-fill-warning-shadow)",
      "sm-error": "0 1px 2px 0 var(--color-fill-error-shadow)",
      "md-error": "0 4px 6px -1px var(--color-fill-error-shadow), 0 2px 4px -2px var(--color-fill-error-shadow)",
      "lg-error": "0 10px 15px -3px var(--color-fill-error-shadow), 0 4px 6px -4px var(--color-fill-error-shadow)",
      "xl-error": "0 20px 25px -5px var(--color-fill-error-shadow), 0 8px 10px -6px var(--color-fill-error-shadow)",
      "sm-notification": "0 1px 2px 0 var(--color-fill-notification-shadow)",
      "md-notification": "0 4px 6px -1px var(--color-fill-notification-shadow), 0 2px 4px -2px var(--color-fill-notification-shadow)",
      "lg-notification": "0 10px 15px -3px var(--color-fill-notification-shadow), 0 4px 6px -4px var(--color-fill-notification-shadow)",
      "xl-notification": "0 20px 25px -5px var(--color-fill-notification-shadow), 0 8px 10px -6px var(--color-fill-notification-shadow)"
    },
    "insetShadow": {
      "sm": "inset 0 1px 2px 0 var(--color-fill-base-shadow)",
      "md": "inset 0 4px 6px 0 var(--color-fill-base-shadow)",
      "lg": "inset 0 6px 6px 0 var(--color-fill-base-shadow)",
      "xl": "inset 0 8px 10px 0 var(--color-fill-base-shadow)",
      "sm-base": "inset 0 1px 2px 0 var(--color-fill-base-shadow)",
      "md-base": "inset 0 4px 6px 0 var(--color-fill-base-shadow)",
      "lg-base": "inset 0 6px 8px 0 var(--color-fill-base-shadow)",
      "xl-base": "inset 0 8px 10px 0 var(--color-fill-base-shadow)",
      "sm-primary": "inset 0 1px 2px 0 var(--color-fill-primary-shadow)",
      "md-primary": "inset 0 4px 6px 0 var(--color-fill-primary-shadow)",
      "lg-primary": "inset 0 6px 8px 0 var(--color-fill-primary-shadow)",
      "xl-primary": "inset 0 8px 10px 0 var(--color-fill-primary-shadow)",
      "sm-secondary": "inset 0 1px 2px 0 var(--color-fill-secondary-shadow)",
      "md-secondary": "inset 0 4px 6px 0 var(--color-fill-secondary-shadow)",
      "lg-secondary": "inset 0 6px 8px 0 var(--color-fill-secondary-shadow)",
      "xl-secondary": "inset 0 8px 10px 0 var(--color-fill-secondary-shadow)",
      "sm-tertiary": "inset 0 1px 2px 0 var(--color-fill-tertiary-shadow)",
      "md-tertiary": "inset 0 4px 6px 0 var(--color-fill-tertiary-shadow)",
      "lg-tertiary": "inset 0 6px 8px 0 var(--color-fill-tertiary-shadow)",
      "xl-tertiary": "inset 0 8px 10px 0 var(--color-fill-tertiary-shadow)",
      "sm-accent": "inset 0 1px 2px 0 var(--color-fill-accent-shadow)",
      "md-accent": "inset 0 4px 6px 0 var(--color-fill-accent-shadow)",
      "lg-accent": "inset 0 6px 8px 0 var(--color-fill-accent-shadow)",
      "xl-accent": "inset 0 8px 10px 0 var(--color-fill-accent-shadow)",
      "sm-muted": "inset 0 1px 2px 0 var(--color-fill-muted-shadow)",
      "md-muted": "inset 0 4px 6px 0 var(--color-fill-muted-shadow)",
      "lg-muted": "inset 0 6px 8px 0 var(--color-fill-muted-shadow)",
      "xl-muted": "inset 0 8px 10px 0 var(--color-fill-muted-shadow)",
      "sm-floor": "inset 0 1px 2px 0 var(--color-fill-floor-shadow)",
      "md-floor": "inset 0 4px 6px 0 var(--color-fill-floor-shadow)",
      "lg-floor": "inset 0 6px 8px 0 var(--color-fill-floor-shadow)",
      "xl-floor": "inset 0 8px 10px 0 var(--color-fill-floor-shadow)",
      "sm-input": "inset 0 1px 2px 0 var(--color-fill-input-shadow)",
      "md-input": "inset 0 4px 6px 0 var(--color-fill-input-shadow)",
      "lg-input": "inset 0 6px 8px 0 var(--color-fill-input-shadow)",
      "xl-input": "inset 0 8px 10px 0 var(--color-fill-input-shadow)",
      "sm-link": "inset 0 1px 2px 0 var(--color-fill-link-shadow)",
      "md-link": "inset 0 4px 6px 0 var(--color-fill-link-shadow)",
      "lg-link": "inset 0 6px 8px 0 var(--color-fill-link-shadow)",
      "xl-link": "inset 0 8px 10px 0 var(--color-fill-link-shadow)",
      "sm-success": "inset 0 1px 2px 0 var(--color-fill-success-shadow)",
      "md-success": "inset 0 4px 6px 0 var(--color-fill-success-shadow)",
      "lg-success": "inset 0 6px 8px 0 var(--color-fill-success-shadow)",
      "xl-success": "inset 0 8px 10px 0 var(--color-fill-success-shadow)",
      "sm-info": "inset 0 1px 2px 0 var(--color-fill-info-shadow)",
      "md-info": "inset 0 4px 6px 0 var(--color-fill-info-shadow)",
      "lg-info": "inset 0 6px 8px 0 var(--color-fill-info-shadow)",
      "xl-info": "inset 0 8px 10px 0 var(--color-fill-info-shadow)",
      "sm-warning": "inset 0 1px 2px 0 var(--color-fill-warning-shadow)",
      "md-warning": "inset 0 4px 6px 0 var(--color-fill-warning-shadow)",
      "lg-warning": "inset 0 6px 8px 0 var(--color-fill-warning-shadow)",
      "xl-warning": "inset 0 8px 10px 0 var(--color-fill-warning-shadow)",
      "sm-error": "inset 0 1px 2px 0 var(--color-fill-error-shadow)",
      "md-error": "inset 0 4px 6px 0 var(--color-fill-error-shadow)",
      "lg-error": "inset 0 6px 8px 0 var(--color-fill-error-shadow)",
      "xl-error": "inset 0 8px 10px 0 var(--color-fill-error-shadow)",
      "sm-notification": "inset 0 1px 2px 0 var(--color-fill-notification-shadow)",
      "md-notification": "inset 0 4px 6px 0 var(--color-fill-notification-shadow)",
      "lg-notification": "inset 0 6px 8px 0 var(--color-fill-notification-shadow)",
      "xl-notification": "inset 0 8px 10px 0 var(--color-fill-notification-shadow)"
    },
    "dropShadow": {
      "sm-base": "0 1px 1px var(--color-fill-base-shadow)",
      "md-base": "0 4px 3px var(--color-fill-base-shadow)",
      "lg-base": "0 10px 8px var(--color-fill-base-shadow)",
      "xl-base": "0 20px 13px var(--color-fill-base-shadow)",
      "sm-primary": "0 1px 1px var(--color-fill-primary-shadow)",
      "md-primary": "0 4px 3px var(--color-fill-primary-shadow)",
      "lg-primary": "0 10px 8px var(--color-fill-primary-shadow)",
      "xl-primary": "0 20px 13px var(--color-fill-primary-shadow)",
      "sm-secondary": "0 1px 1px var(--color-fill-secondary-shadow)",
      "md-secondary": "0 4px 3px var(--color-fill-secondary-shadow)",
      "lg-secondary": "0 10px 8px var(--color-fill-secondary-shadow)",
      "xl-secondary": "0 20px 13px var(--color-fill-secondary-shadow)",
      "sm-tertiary": "0 1px 1px var(--color-fill-tertiary-shadow)",
      "md-tertiary": "0 4px 3px var(--color-fill-tertiary-shadow)",
      "lg-tertiary": "0 10px 8px var(--color-fill-tertiary-shadow)",
      "xl-tertiary": "0 20px 13px var(--color-fill-tertiary-shadow)",
      "sm-accent": "0 1px 1px var(--color-fill-accent-shadow)",
      "md-accent": "0 4px 3px var(--color-fill-accent-shadow)",
      "lg-accent": "0 10px 8px var(--color-fill-accent-shadow)",
      "xl-accent": "0 20px 13px var(--color-fill-accent-shadow)",
      "sm-muted": "0 1px 1px var(--color-fill-muted-shadow)",
      "md-muted": "0 4px 3px var(--color-fill-muted-shadow)",
      "lg-muted": "0 10px 8px var(--color-fill-muted-shadow)",
      "xl-muted": "0 20px 13px var(--color-fill-muted-shadow)",
      "sm-floor": "0 1px 1px var(--color-fill-floor-shadow)",
      "md-floor": "0 4px 3px var(--color-fill-floor-shadow)",
      "lg-floor": "0 10px 8px var(--color-fill-floor-shadow)",
      "xl-floor": "0 20px 13px var(--color-fill-floor-shadow)",
      "sm-input": "0 1px 1px var(--color-fill-input-shadow)",
      "md-input": "0 4px 3px var(--color-fill-input-shadow)",
      "lg-input": "0 10px 8px var(--color-fill-input-shadow)",
      "xl-input": "0 20px 13px var(--color-fill-input-shadow)",
      "sm-link": "0 1px 1px var(--color-fill-link-shadow)",
      "md-link": "0 4px 3px var(--color-fill-link-shadow)",
      "lg-link": "0 10px 8px var(--color-fill-link-shadow)",
      "xl-link": "0 20px 13px var(--color-fill-link-shadow)",
      "sm-success": "0 1px 1px var(--color-fill-success-shadow)",
      "md-success": "0 4px 3px var(--color-fill-success-shadow)",
      "lg-success": "0 10px 8px var(--color-fill-success-shadow)",
      "xl-success": "0 20px 13px var(--color-fill-success-shadow)",
      "sm-info": "0 1px 1px var(--color-fill-info-shadow)",
      "md-info": "0 4px 3px var(--color-fill-info-shadow)",
      "lg-info": "0 10px 8px var(--color-fill-info-shadow)",
      "xl-info": "0 20px 13px var(--color-fill-info-shadow)",
      "sm-warning": "0 1px 1px var(--color-fill-warning-shadow)",
      "md-warning": "0 4px 3px var(--color-fill-warning-shadow)",
      "lg-warning": "0 10px 8px var(--color-fill-warning-shadow)",
      "xl-warning": "0 20px 13px var(--color-fill-warning-shadow)",
      "sm-error": "0 1px 1px var(--color-fill-error-shadow)",
      "md-error": "0 4px 3px var(--color-fill-error-shadow)",
      "lg-error": "0 10px 8px var(--color-fill-error-shadow)",
      "xl-error": "0 20px 13px var(--color-fill-error-shadow)",
      "sm-notification": "0 1px 1px var(--color-fill-notification-shadow)",
      "md-notification": "0 4px 3px var(--color-fill-notification-shadow)",
      "lg-notification": "0 10px 8px var(--color-fill-notification-shadow)",
      "xl-notification": "0 20px 13px var(--color-fill-notification-shadow)"
    },
    "textShadow": {
      "sm-base": "0 1px 2px var(--color-pen-base-shadow)",
      "md-base": "0 2px 4px var(--color-pen-base-shadow)",
      "lg-base": "0 4px 8px var(--color-pen-base-shadow)",
      "xl-base": "0 8px 16px var(--color-pen-base-shadow)",
      "sm-primary": "0 1px 2px var(--color-pen-primary-shadow)",
      "md-primary": "0 2px 4px var(--color-pen-primary-shadow)",
      "lg-primary": "0 4px 8px var(--color-pen-primary-shadow)",
      "xl-primary": "0 8px 16px var(--color-pen-primary-shadow)",
      "sm-secondary": "0 1px 2px var(--color-pen-secondary-shadow)",
      "md-secondary": "0 2px 4px var(--color-pen-secondary-shadow)",
      "lg-secondary": "0 4px 8px var(--color-pen-secondary-shadow)",
      "xl-secondary": "0 8px 16px var(--color-pen-secondary-shadow)",
      "sm-tertiary": "0 1px 2px var(--color-pen-tertiary-shadow)",
      "md-tertiary": "0 2px 4px var(--color-pen-tertiary-shadow)",
      "lg-tertiary": "0 4px 8px var(--color-pen-tertiary-shadow)",
      "xl-tertiary": "0 8px 16px var(--color-pen-tertiary-shadow)",
      "sm-accent": "0 1px 2px var(--color-pen-accent-shadow)",
      "md-accent": "0 2px 4px var(--color-pen-accent-shadow)",
      "lg-accent": "0 4px 8px var(--color-pen-accent-shadow)",
      "xl-accent": "0 8px 16px var(--color-pen-accent-shadow)",
      "sm-muted": "0 1px 2px var(--color-pen-muted-shadow)",
      "md-muted": "0 2px 4px var(--color-pen-muted-shadow)",
      "lg-muted": "0 4px 8px var(--color-pen-muted-shadow)",
      "xl-muted": "0 8px 16px var(--color-pen-muted-shadow)",
      "sm-floor": "0 1px 2px var(--color-pen-floor-shadow)",
      "md-floor": "0 2px 4px var(--color-pen-floor-shadow)",
      "lg-floor": "0 4px 8px var(--color-pen-floor-shadow)",
      "xl-floor": "0 8px 16px var(--color-pen-floor-shadow)",
      "sm-input": "0 1px 2px var(--color-pen-input-shadow)",
      "md-input": "0 2px 4px var(--color-pen-input-shadow)",
      "lg-input": "0 4px 8px var(--color-pen-input-shadow)",
      "xl-input": "0 8px 16px var(--color-pen-input-shadow)",
      "sm-link": "0 1px 2px var(--color-pen-link-shadow)",
      "md-link": "0 2px 4px var(--color-pen-link-shadow)",
      "lg-link": "0 4px 8px var(--color-pen-link-shadow)",
      "xl-link": "0 8px 16px var(--color-pen-link-shadow)",
      "sm-success": "0 1px 2px var(--color-pen-success-shadow)",
      "md-success": "0 2px 4px var(--color-pen-success-shadow)",
      "lg-success": "0 4px 8px var(--color-pen-success-shadow)",
      "xl-success": "0 8px 16px var(--color-pen-success-shadow)",
      "sm-info": "0 1px 2px var(--color-pen-info-shadow)",
      "md-info": "0 2px 4px var(--color-pen-info-shadow)",
      "lg-info": "0 4px 8px var(--color-pen-info-shadow)",
      "xl-info": "0 8px 16px var(--color-pen-info-shadow)",
      "sm-warning": "0 1px 2px var(--color-pen-warning-shadow)",
      "md-warning": "0 2px 4px var(--color-pen-warning-shadow)",
      "lg-warning": "0 4px 8px var(--color-pen-warning-shadow)",
      "xl-warning": "0 8px 16px var(--color-pen-warning-shadow)",
      "sm-error": "0 1px 2px var(--color-pen-error-shadow)",
      "md-error": "0 2px 4px var(--color-pen-error-shadow)",
      "lg-error": "0 4px 8px var(--color-pen-error-shadow)",
      "xl-error": "0 8px 16px var(--color-pen-error-shadow)",
      "sm-notification": "0 1px 2px var(--color-pen-notification-shadow)",
      "md-notification": "0 2px 4px var(--color-pen-notification-shadow)",
      "lg-notification": "0 4px 8px var(--color-pen-notification-shadow)",
      "xl-notification": "0 8px 16px var(--color-pen-notification-shadow)"
    }
  },
  "responsive": {
    "breakpoints": {
      "sm": "640px",
      "md": "768px",
      "lg": "1024px",
      "xl": "1280px",
      "2xl": "1536px",
      "3xl": "1920px",
      "4xl": "2560px",
      "5xl": "3840px"
    },
    "containers": {
      "center": "true",
      "2xl": "1536px"
    }
  },
  "assets": {}
} as const
const canonicalModes = {
  "light": {
    "fill-base": {
      "default": "#ffffff",
      "hover": "#f5f5f5",
      "active": "#e5e5e5",
      "selected": "#e5e5e5",
      "visited": "#ffffff",
      "disabled": "#f5f5f5",
      "shadow": "#a3a3a3"
    },
    "fill-primary": {
      "default": "#94b99d",
      "hover": "#83a78d",
      "active": "#6b9075",
      "selected": "#6b9075",
      "visited": "#94b99d",
      "disabled": "#e5e5e5",
      "shadow": "#a3a3a3"
    },
    "fill-secondary": {
      "default": "#caa7d9",
      "hover": "#b996c6",
      "active": "#a883b3",
      "selected": "#a883b3",
      "visited": "#caa7d9",
      "disabled": "#e5e5e5",
      "shadow": "#a3a3a3"
    },
    "fill-tertiary": {
      "default": "#e5e5e5",
      "hover": "#d4d4d4",
      "active": "#a3a3a3",
      "selected": "#a3a3a3",
      "visited": "#e5e5e5",
      "disabled": "#f5f5f5",
      "shadow": "#a3a3a3"
    },
    "fill-accent": {
      "default": "#a5c6ad",
      "hover": "#94b99d",
      "active": "#83a78d",
      "selected": "#83a78d",
      "visited": "#a5c6ad",
      "disabled": "#e5e5e5",
      "shadow": "#a3a3a3"
    },
    "fill-muted": {
      "default": "#e5e5e5",
      "hover": "#d4d4d4",
      "active": "#a3a3a3",
      "selected": "#a3a3a3",
      "visited": "#e5e5e5",
      "disabled": "#f5f5f5",
      "shadow": "#a3a3a3"
    },
    "fill-floor": {
      "default": "#f5f5f5",
      "hover": "#f5f5f5",
      "active": "#f5f5f5",
      "selected": "#f5f5f5",
      "visited": "#f5f5f5",
      "disabled": "#f5f5f5",
      "shadow": "#a3a3a3"
    },
    "fill-input": {
      "default": "#fafafa",
      "hover": "#ffffff",
      "active": "#fafafa",
      "selected": "#fafafa",
      "visited": "#fafafa",
      "disabled": "#e5e5e5",
      "shadow": "#00000000"
    },
    "fill-link": {
      "default": "#94b99d",
      "hover": "#83a78d",
      "active": "#6b9075",
      "selected": "#6b9075",
      "visited": "#94b99d",
      "disabled": "#e5e5e5",
      "shadow": "#a3a3a3"
    },
    "fill-success": {
      "default": "#dcfce7",
      "hover": "#bbf7d0",
      "active": "#86efac",
      "selected": "#86efac",
      "visited": "#dcfce7",
      "disabled": "#f5f5f5",
      "shadow": "#a3a3a3"
    },
    "fill-info": {
      "default": "#dbeafe",
      "hover": "#bfdbfe",
      "active": "#93c5fd",
      "selected": "#93c5fd",
      "visited": "#dbeafe",
      "disabled": "#f5f5f5",
      "shadow": "#a3a3a3"
    },
    "fill-warning": {
      "default": "#fef9c3",
      "hover": "#fef08a",
      "active": "#fde047",
      "selected": "#fde047",
      "visited": "#fef9c3",
      "disabled": "#f5f5f5",
      "shadow": "#a3a3a3"
    },
    "fill-error": {
      "default": "#fee2e2",
      "hover": "#fecaca",
      "active": "#fca5a5",
      "selected": "#fca5a5",
      "visited": "#fee2e2",
      "disabled": "#f5f5f5",
      "shadow": "#a3a3a3"
    },
    "fill-notification": {
      "default": "#ede9fe",
      "hover": "#ddd6fe",
      "active": "#c4b5fd",
      "selected": "#c4b5fd",
      "visited": "#ede9fe",
      "disabled": "#f5f5f5",
      "shadow": "#a3a3a3"
    },
    "pen-base": {
      "default": "#262626",
      "hover": "#000000",
      "active": "#000000",
      "selected": "#000000",
      "visited": "#262626",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-primary": {
      "default": "#405546",
      "hover": "#2c3a30",
      "active": "#1a201c",
      "selected": "#1a201c",
      "visited": "#405546",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-secondary": {
      "default": "#704a77",
      "hover": "#59395f",
      "active": "#422946",
      "selected": "#422946",
      "visited": "#704a77",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-tertiary": {
      "default": "#737373",
      "hover": "#525252",
      "active": "#262626",
      "selected": "#262626",
      "visited": "#737373",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-accent": {
      "default": "#587460",
      "hover": "#405546",
      "active": "#2c3a30",
      "selected": "#2c3a30",
      "visited": "#587460",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-muted": {
      "default": "#737373",
      "hover": "#525252",
      "active": "#262626",
      "selected": "#262626",
      "visited": "#737373",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-floor": {
      "default": "#525252",
      "hover": "#262626",
      "active": "#000000",
      "selected": "#000000",
      "visited": "#525252",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-input": {
      "default": "#262626",
      "hover": "#000000",
      "active": "#000000",
      "selected": "#000000",
      "visited": "#262626",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-link": {
      "default": "#405546",
      "hover": "#2c3a30",
      "active": "#262626",
      "selected": "#262626",
      "visited": "#405546",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-success": {
      "default": "#166534",
      "hover": "#14532d",
      "active": "#052e16",
      "selected": "#052e16",
      "visited": "#166534",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-info": {
      "default": "#1e40af",
      "hover": "#1e3a8a",
      "active": "#172554",
      "selected": "#172554",
      "visited": "#1e40af",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-warning": {
      "default": "#854d0e",
      "hover": "#713f12",
      "active": "#422006",
      "selected": "#422006",
      "visited": "#854d0e",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-error": {
      "default": "#991b1b",
      "hover": "#7f1d1d",
      "active": "#450a0a",
      "selected": "#450a0a",
      "visited": "#991b1b",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "pen-notification": {
      "default": "#581c87",
      "hover": "#4c1d95",
      "active": "#3b0764",
      "selected": "#3b0764",
      "visited": "#581c87",
      "disabled": "#a3a3a3",
      "shadow": "#a3a3a3"
    },
    "edge-base": {
      "default": "#d4d4d4",
      "hover": "#94b99d",
      "active": "#6b9075",
      "selected": "#6b9075",
      "visited": "#d4d4d4",
      "disabled": "#e5e5e5"
    },
    "edge-primary": {
      "default": "#83a78d",
      "hover": "#6b9075",
      "active": "#587460",
      "selected": "#587460",
      "visited": "#83a78d",
      "disabled": "#e5e5e5"
    },
    "edge-secondary": {
      "default": "#b996c6",
      "hover": "#a883b3",
      "active": "#9770a1",
      "selected": "#9770a1",
      "visited": "#b996c6",
      "disabled": "#e5e5e5"
    },
    "edge-tertiary": {
      "default": "#d4d4d4",
      "hover": "#a3a3a3",
      "active": "#737373",
      "selected": "#737373",
      "visited": "#d4d4d4",
      "disabled": "#e5e5e5"
    },
    "edge-accent": {
      "default": "#94b99d",
      "hover": "#83a78d",
      "active": "#6b9075",
      "selected": "#6b9075",
      "visited": "#94b99d",
      "disabled": "#e5e5e5"
    },
    "edge-muted": {
      "default": "#d4d4d4",
      "hover": "#a3a3a3",
      "active": "#737373",
      "selected": "#737373",
      "visited": "#d4d4d4",
      "disabled": "#e5e5e5"
    },
    "edge-floor": {
      "default": "#e5e5e5",
      "hover": "#d4d4d4",
      "active": "#a3a3a3",
      "selected": "#a3a3a3",
      "visited": "#e5e5e5",
      "disabled": "#f5f5f5"
    },
    "edge-input": {
      "default": "#d4d4d4",
      "hover": "#94b99d",
      "active": "#6b9075",
      "selected": "#6b9075",
      "visited": "#d4d4d4",
      "disabled": "#e5e5e5"
    },
    "edge-link": {
      "default": "#83a78d",
      "hover": "#6b9075",
      "active": "#587460",
      "selected": "#587460",
      "visited": "#83a78d",
      "disabled": "#e5e5e5"
    },
    "edge-success": {
      "default": "#86efac",
      "hover": "#4ade80",
      "active": "#22c55e",
      "selected": "#22c55e",
      "visited": "#86efac",
      "disabled": "#e5e5e5"
    },
    "edge-info": {
      "default": "#93c5fd",
      "hover": "#60a5fa",
      "active": "#3b82f6",
      "selected": "#3b82f6",
      "visited": "#93c5fd",
      "disabled": "#e5e5e5"
    },
    "edge-warning": {
      "default": "#fde047",
      "hover": "#facc15",
      "active": "#eab308",
      "selected": "#eab308",
      "visited": "#fde047",
      "disabled": "#e5e5e5"
    },
    "edge-error": {
      "default": "#fca5a5",
      "hover": "#f87171",
      "active": "#ef4444",
      "selected": "#ef4444",
      "visited": "#fca5a5",
      "disabled": "#e5e5e5"
    },
    "edge-notification": {
      "default": "#c4b5fd",
      "hover": "#a78bfa",
      "active": "#8b5cf6",
      "selected": "#8b5cf6",
      "visited": "#c4b5fd",
      "disabled": "#e5e5e5"
    }
  },
  "dark": {
    "fill-base": {
      "default": "#171717",
      "hover": "#262626",
      "active": "#404040",
      "selected": "#404040",
      "visited": "#171717",
      "disabled": "#262626",
      "shadow": "#000000"
    },
    "fill-primary": {
      "default": "#94b99d",
      "hover": "#a5c6ad",
      "active": "#b6d3bd",
      "selected": "#b6d3bd",
      "visited": "#94b99d",
      "disabled": "#404040",
      "shadow": "#000000"
    },
    "fill-secondary": {
      "default": "#caa7d9",
      "hover": "#d2b8e0",
      "active": "#dbc9e7",
      "selected": "#dbc9e7",
      "visited": "#caa7d9",
      "disabled": "#404040",
      "shadow": "#000000"
    },
    "fill-tertiary": {
      "default": "#404040",
      "hover": "#525252",
      "active": "#737373",
      "selected": "#737373",
      "visited": "#404040",
      "disabled": "#262626",
      "shadow": "#000000"
    },
    "fill-accent": {
      "default": "#a5c6ad",
      "hover": "#b6d3bd",
      "active": "#c7dfce",
      "selected": "#c7dfce",
      "visited": "#a5c6ad",
      "disabled": "#404040",
      "shadow": "#000000"
    },
    "fill-muted": {
      "default": "#404040",
      "hover": "#525252",
      "active": "#737373",
      "selected": "#737373",
      "visited": "#404040",
      "disabled": "#262626",
      "shadow": "#000000"
    },
    "fill-floor": {
      "default": "#0a0a0a",
      "hover": "#0a0a0a",
      "active": "#0a0a0a",
      "selected": "#0a0a0a",
      "visited": "#0a0a0a",
      "disabled": "#0a0a0a",
      "shadow": "#000000"
    },
    "fill-input": {
      "default": "#262626",
      "hover": "#404040",
      "active": "#262626",
      "selected": "#262626",
      "visited": "#262626",
      "disabled": "#404040",
      "shadow": "#00000000"
    },
    "fill-link": {
      "default": "#94b99d",
      "hover": "#a5c6ad",
      "active": "#b6d3bd",
      "selected": "#b6d3bd",
      "visited": "#94b99d",
      "disabled": "#404040",
      "shadow": "#000000"
    },
    "fill-success": {
      "default": "#14532d",
      "hover": "#166534",
      "active": "#15803d",
      "selected": "#15803d",
      "visited": "#14532d",
      "disabled": "#262626",
      "shadow": "#000000"
    },
    "fill-info": {
      "default": "#1e3a8a",
      "hover": "#1e40af",
      "active": "#1d4ed8",
      "selected": "#1d4ed8",
      "visited": "#1e3a8a",
      "disabled": "#262626",
      "shadow": "#000000"
    },
    "fill-warning": {
      "default": "#78350f",
      "hover": "#854d0e",
      "active": "#a16207",
      "selected": "#a16207",
      "visited": "#78350f",
      "disabled": "#262626",
      "shadow": "#000000"
    },
    "fill-error": {
      "default": "#7f1d1d",
      "hover": "#991b1b",
      "active": "#b91c1c",
      "selected": "#b91c1c",
      "visited": "#7f1d1d",
      "disabled": "#262626",
      "shadow": "#000000"
    },
    "fill-notification": {
      "default": "#4a044e",
      "hover": "#581c87",
      "active": "#6b21a8",
      "selected": "#6b21a8",
      "visited": "#4a044e",
      "disabled": "#262626",
      "shadow": "#000000"
    },
    "pen-base": {
      "default": "#f5f5f5",
      "hover": "#ffffff",
      "active": "#ffffff",
      "selected": "#ffffff",
      "visited": "#f5f5f5",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-primary": {
      "default": "#a5c6ad",
      "hover": "#b6d3bd",
      "active": "#c7dfce",
      "selected": "#c7dfce",
      "visited": "#a5c6ad",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-secondary": {
      "default": "#d2b8e0",
      "hover": "#dbc9e7",
      "active": "#e8dbf1",
      "selected": "#e8dbf1",
      "visited": "#d2b8e0",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-tertiary": {
      "default": "#a3a3a3",
      "hover": "#d4d4d4",
      "active": "#f5f5f5",
      "selected": "#f5f5f5",
      "visited": "#a3a3a3",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-accent": {
      "default": "#b6d3bd",
      "hover": "#c7dfce",
      "active": "#daebde",
      "selected": "#daebde",
      "visited": "#b6d3bd",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-muted": {
      "default": "#737373",
      "hover": "#a3a3a3",
      "active": "#d4d4d4",
      "selected": "#d4d4d4",
      "visited": "#737373",
      "disabled": "#525252",
      "shadow": "#000000"
    },
    "pen-floor": {
      "default": "#a3a3a3",
      "hover": "#d4d4d4",
      "active": "#f5f5f5",
      "selected": "#f5f5f5",
      "visited": "#a3a3a3",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-input": {
      "default": "#f5f5f5",
      "hover": "#ffffff",
      "active": "#ffffff",
      "selected": "#ffffff",
      "visited": "#f5f5f5",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-link": {
      "default": "#a5c6ad",
      "hover": "#b6d3bd",
      "active": "#f5f5f5",
      "selected": "#f5f5f5",
      "visited": "#a5c6ad",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-success": {
      "default": "#bbf7d0",
      "hover": "#dcfce7",
      "active": "#f0fdf4",
      "selected": "#f0fdf4",
      "visited": "#bbf7d0",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-info": {
      "default": "#bfdbfe",
      "hover": "#dbeafe",
      "active": "#eff6ff",
      "selected": "#eff6ff",
      "visited": "#bfdbfe",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-warning": {
      "default": "#fef08a",
      "hover": "#fef9c3",
      "active": "#fefce8",
      "selected": "#fefce8",
      "visited": "#fef08a",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-error": {
      "default": "#fecaca",
      "hover": "#fee2e2",
      "active": "#fef2f2",
      "selected": "#fef2f2",
      "visited": "#fecaca",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "pen-notification": {
      "default": "#ddd6fe",
      "hover": "#ede9fe",
      "active": "#f5f3ff",
      "selected": "#f5f3ff",
      "visited": "#ddd6fe",
      "disabled": "#737373",
      "shadow": "#000000"
    },
    "edge-base": {
      "default": "#525252",
      "hover": "#94b99d",
      "active": "#a5c6ad",
      "selected": "#a5c6ad",
      "visited": "#525252",
      "disabled": "#404040"
    },
    "edge-primary": {
      "default": "#83a78d",
      "hover": "#94b99d",
      "active": "#a5c6ad",
      "selected": "#a5c6ad",
      "visited": "#83a78d",
      "disabled": "#525252"
    },
    "edge-secondary": {
      "default": "#b996c6",
      "hover": "#caa7d9",
      "active": "#d2b8e0",
      "selected": "#d2b8e0",
      "visited": "#b996c6",
      "disabled": "#525252"
    },
    "edge-tertiary": {
      "default": "#525252",
      "hover": "#737373",
      "active": "#a3a3a3",
      "selected": "#a3a3a3",
      "visited": "#525252",
      "disabled": "#404040"
    },
    "edge-accent": {
      "default": "#94b99d",
      "hover": "#a5c6ad",
      "active": "#b6d3bd",
      "selected": "#b6d3bd",
      "visited": "#94b99d",
      "disabled": "#525252"
    },
    "edge-muted": {
      "default": "#525252",
      "hover": "#737373",
      "active": "#a3a3a3",
      "selected": "#a3a3a3",
      "visited": "#525252",
      "disabled": "#404040"
    },
    "edge-floor": {
      "default": "#404040",
      "hover": "#525252",
      "active": "#737373",
      "selected": "#737373",
      "visited": "#404040",
      "disabled": "#262626"
    },
    "edge-input": {
      "default": "#525252",
      "hover": "#94b99d",
      "active": "#a5c6ad",
      "selected": "#a5c6ad",
      "visited": "#525252",
      "disabled": "#404040"
    },
    "edge-link": {
      "default": "#94b99d",
      "hover": "#a5c6ad",
      "active": "#b6d3bd",
      "selected": "#b6d3bd",
      "visited": "#94b99d",
      "disabled": "#525252"
    },
    "edge-success": {
      "default": "#22c55e",
      "hover": "#4ade80",
      "active": "#86efac",
      "selected": "#86efac",
      "visited": "#22c55e",
      "disabled": "#525252"
    },
    "edge-info": {
      "default": "#3b82f6",
      "hover": "#60a5fa",
      "active": "#93c5fd",
      "selected": "#93c5fd",
      "visited": "#3b82f6",
      "disabled": "#525252"
    },
    "edge-warning": {
      "default": "#eab308",
      "hover": "#facc15",
      "active": "#fde047",
      "selected": "#fde047",
      "visited": "#eab308",
      "disabled": "#525252"
    },
    "edge-error": {
      "default": "#ef4444",
      "hover": "#f87171",
      "active": "#fca5a5",
      "selected": "#fca5a5",
      "visited": "#ef4444",
      "disabled": "#525252"
    },
    "edge-notification": {
      "default": "#8b5cf6",
      "hover": "#a78bfa",
      "active": "#c4b5fd",
      "selected": "#c4b5fd",
      "visited": "#8b5cf6",
      "disabled": "#525252"
    }
  }
} as const

export function createCanonicalThemeDefinition(options: { id?: string; name?: string; description?: string; ownerType?: ThemeOwnerType; ownerId?: string } = {}): ThemeDefinition {
  const ownerType = options.ownerType ?? 'system'
  if (ownerType !== 'system' && !options.ownerId) throw new TypeError('ownerId is required for non-system canonical themes.')
  return structuredClone({
    id: options.id ?? 'theme-manager-default',
    name: options.name ?? 'Theme Manager Default',
    description: options.description ?? 'Canonical complete Theme Manager presentation vocabulary.',
    version: '1.0.0',
    schemaVersion: '1',
    ownership: { ownerType, ...(options.ownerId ? { ownerId: options.ownerId } : {}) },
    visibility: ownerType === 'system' ? 'system' : 'private',
    lifecycle: ownerType === 'system' ? 'published' : 'draft',
    presentation: canonicalPresentation,
    modes: canonicalModes,
  }) as ThemeDefinition
}
